/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgAbout.java
 *
 * Created on 23 Jun 10, 19:03:08
 */

package khanzahms;

/**
 *
 * @author perpustakaan
 */
public class DlgAbout extends javax.swing.JDialog {

    private static DlgAbout myInstance;
    public DlgAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(10,10);
        setSize(465,515);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        jLabel6 = new javax.swing.JLabel();
        panelGlass1 = new usu.widget.glass.PanelGlass();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelGlass3 = new usu.widget.glass.PanelGlass();
        BtnKeluar = new widget.Button();
        jLabel21 = new javax.swing.JLabel();
        panelGlass4 = new usu.widget.glass.PanelGlass();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        panelGlass5 = new usu.widget.glass.PanelGlass();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("::[ About Program ]::");
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ About Program ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 70, 40))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(50, 70, 50));
        jLabel6.setText(".: Aplikasi ");
        jLabel6.setName("jLabel6"); // NOI18N
        internalFrame1.add(jLabel6);
        jLabel6.setBounds(10, 18, 90, 20);

        panelGlass1.setBackground(new java.awt.Color(235, 255, 235));
        panelGlass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(215, 235, 205)));
        panelGlass1.setOpaqueImage(false);
        panelGlass1.setRound(false);
        panelGlass1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(50, 70, 50));
        jLabel4.setText("Server : MySQL Server");
        jLabel4.setName("jLabel4"); // NOI18N
        panelGlass1.add(jLabel4);
        jLabel4.setBounds(69, 22, 170, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(50, 70, 50));
        jLabel7.setText("Nama Aplikasi : Khanza HMS 2013");
        jLabel7.setName("jLabel7"); // NOI18N
        panelGlass1.add(jLabel7);
        jLabel7.setBounds(36, 8, 200, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(50, 70, 50));
        jLabel8.setText("Default Database : sik");
        jLabel8.setName("jLabel8"); // NOI18N
        panelGlass1.add(jLabel8);
        jLabel8.setBounds(17, 36, 170, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(50, 70, 50));
        jLabel9.setText("File Konfigurasi : database.xml");
        jLabel9.setName("jLabel9"); // NOI18N
        panelGlass1.add(jLabel9);
        jLabel9.setBounds(29, 50, 170, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(50, 70, 50));
        jLabel10.setText("Default Port : 3306");
        jLabel10.setName("jLabel10"); // NOI18N
        panelGlass1.add(jLabel10);
        jLabel10.setBounds(43, 64, 170, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(50, 70, 50));
        jLabel11.setText("Untuk mensetting aplikasi menjadi Client");
        jLabel11.setName("jLabel11"); // NOI18N
        panelGlass1.add(jLabel11);
        jLabel11.setBounds(230, 8, 210, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(50, 70, 50));
        jLabel12.setText("Server, ganti HOST Localhost dengan");
        jLabel12.setName("jLabel12"); // NOI18N
        panelGlass1.add(jLabel12);
        jLabel12.setBounds(230, 22, 200, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(50, 70, 50));
        jLabel13.setText("alamat/IP Address dari server yang di");
        jLabel13.setName("jLabel13"); // NOI18N
        panelGlass1.add(jLabel13);
        jLabel13.setBounds(230, 36, 200, 14);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(50, 70, 50));
        jLabel14.setText("gunakan. Jagan lupa untuk mengatur hak");
        jLabel14.setName("jLabel14"); // NOI18N
        panelGlass1.add(jLabel14);
        jLabel14.setBounds(230, 50, 220, 14);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(50, 70, 50));
        jLabel15.setText("akses di MySQL server agar terkoneksi");
        jLabel15.setName("jLabel15"); // NOI18N
        panelGlass1.add(jLabel15);
        jLabel15.setBounds(230, 64, 210, 14);

        internalFrame1.add(panelGlass1);
        panelGlass1.setBounds(7, 38, 454, 90);

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(50, 70, 50));
        jLabel16.setText(".: Developer");
        jLabel16.setName("jLabel16"); // NOI18N
        internalFrame1.add(jLabel16);
        jLabel16.setBounds(10, 135, 110, 20);

        panelGlass3.setBackground(new java.awt.Color(235, 255, 235));
        panelGlass3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(215, 235, 205)));
        panelGlass3.setOpaqueImage(false);
        panelGlass3.setRound(false);
        panelGlass3.setLayout(null);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Close");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setIconTextGap(3);
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass3.add(BtnKeluar);
        BtnKeluar.setBounds(340, 10, 100, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(50, 70, 50));
        jLabel21.setText("Programmer : elkhanza, khanza_media@yahoo.com");
        jLabel21.setName("jLabel21"); // NOI18N
        panelGlass3.add(jLabel21);
        jLabel21.setBounds(30, 20, 300, 14);

        internalFrame1.add(panelGlass3);
        panelGlass3.setBounds(7, 360, 454, 52);

        panelGlass4.setBackground(new java.awt.Color(235, 255, 235));
        panelGlass4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(215, 235, 205)));
        panelGlass4.setOpaqueImage(false);
        panelGlass4.setRound(false);
        panelGlass4.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(50, 70, 50));
        jLabel19.setText("Phone : 08562675039");
        jLabel19.setName("jLabel19"); // NOI18N
        panelGlass4.add(jLabel19);
        jLabel19.setBounds(270, 160, 200, 14);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(50, 70, 50));
        jLabel24.setText("Blog http://elkhanza.wordpress.com");
        jLabel24.setName("jLabel24"); // NOI18N
        panelGlass4.add(jLabel24);
        jLabel24.setBounds(10, 160, 260, 14);

        panelGlass5.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass5.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass5.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass5.setRound(false);
        panelGlass5.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass5.setLayout(null);
        panelGlass4.add(panelGlass5);
        panelGlass5.setBounds(10, 20, 410, 110);

        internalFrame1.add(panelGlass4);
        panelGlass4.setBounds(7, 155, 454, 200);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        dispose();
}//GEN-LAST:event_BtnKeluarKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgAbout dialog = new DlgAbout(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private usu.widget.glass.PanelGlass panelGlass1;
    private usu.widget.glass.PanelGlass panelGlass3;
    private usu.widget.glass.PanelGlass panelGlass4;
    private usu.widget.glass.PanelGlass panelGlass5;
    // End of variables declaration//GEN-END:variables

}
