package khanzahms;
import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import khanzahms.DlgHarian;

public class DlgBulanan extends javax.swing.JDialog {
    private Connection connect=koneksiDB.condb();
    private DefaultTableModel tabMode;
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();

    /** Creates new form DlgProgramStudi */
    public DlgBulanan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocation(8,1);
        setSize(885,674);
        Object[] row={"<html><font color='#b95656' face='Tahoma' size='3'>NIK",
                      "<html><font color='#b95656' face='Tahoma' size='3'>Nama",
                      "<html><font color='#b95656' face='Tahoma' size='3'>Shift",
                      "<html><font color='#b95656' face='Tahoma' size='3'>Jam Datang",
                      "<html><font color='#b95656' face='Tahoma' size='3'>Jam Pulang",
                      "<html><font color='#b95656' face='Tahoma' size='3'>Status",
                      "<html><font color='#b95656' face='Tahoma' size='3'>Keterlambatan",
                      "<html><font color='#b95656' face='Tahoma' size='3'>Durasi",
                      "<html><font color='#b95656' face='Tahoma' size='3'>Catatan"};
        tabMode=new DefaultTableModel(null,row){
              @Override public boolean isCellEditable(int rowIndex, int colIndex){return false;}
        };

        tbPegawai.setModel(tabMode);
        tbPegawai.setPreferredScrollableViewportSize(new Dimension(500,500));
        tbPegawai.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (int i = 0; i < 9; i++) {
            TableColumn column = tbPegawai.getColumnModel().getColumn(i);
            if(i==0){
                column.setPreferredWidth(100);
            }else if(i==1){
                column.setPreferredWidth(300);
            }else if(i==2){
                column.setPreferredWidth(80);
            }else if(i==3){
                column.setPreferredWidth(150);
            }else if(i==4){
                column.setPreferredWidth(150);
            }else if(i==5){
                column.setPreferredWidth(80);
            }else if(i==6){
                column.setPreferredWidth(90);
            }else if(i==7){
                column.setPreferredWidth(80);
            }else if(i==8){
                column.setPreferredWidth(300);
            }
        }
        tbPegawai.setDefaultRenderer(Object.class, new WarnaTable());

        Nik.setDocument(new batasInput((int)25).getKata(Nik));
        catatan.setDocument(new batasInput((int)100).getKata(catatan));
        
        TCari.setDocument(new batasInput((int)100).getKata(TCari));
        
        Idpresensi.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {isBar();}
            @Override
            public void removeUpdate(DocumentEvent e) {isBar();}
            @Override
            public void changedUpdate(DocumentEvent e) {isBar();}

        });
        
        bar.getButton().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Idpresensi.setText(bar.getTextField().getText());
            }
        });
        
        
        
        DlgInput.setSize(744,234);
        DlgInput.setVisible(false);
        
        loadTahun();
    }
    private Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();
    DlgBarcode bar=new DlgBarcode(null,false);
    private String[] id;
    private String[] tgl;
    
    int no=0;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DlgInput = new javax.swing.JDialog();
        panelJudul2 = new widget.PanelJudul();
        lblKtg = new widget.Label();
        jLabel3 = new widget.Label();
        panel2 = new widget.Panel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new widget.Label();
        internalFrame2 = new widget.InternalFrame();
        BtnClose = new widget.Button();
        BtnBatal = new widget.Button();
        label2 = new widget.Label();
        label23 = new widget.Label();
        Nm = new widget.TextBox();
        Cari = new widget.Button();
        Nik = new widget.TextBox();
        tglMasuk = new widget.Tanggal();
        Jam = new widget.ComboBox();
        label26 = new widget.Label();
        Menit = new widget.ComboBox();
        Detik = new widget.ComboBox();
        Jam2 = new widget.ComboBox();
        Menit2 = new widget.ComboBox();
        Detik2 = new widget.ComboBox();
        label28 = new widget.Label();
        tglPulang = new widget.Tanggal();
        BtnSimpan = new widget.Button();
        label24 = new widget.Label();
        catatan = new widget.TextBox();
        label25 = new widget.Label();
        Shift = new widget.ComboBox();
        jamdatang = new widget.TextBox();
        jampulang = new widget.TextBox();
        Idpresensi = new widget.TextBox();
        internalFrame1 = new widget.InternalFrame();
        jPanel2 = new widget.panelisi();
        jPanel4 = new widget.panelisi();
        label11 = new widget.Label();
        ThnCari = new widget.ComboBox();
        BlnCari = new widget.ComboBox();
        label9 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        label10 = new widget.Label();
        LCount = new widget.Label();
        jPanel5 = new widget.panelisi();
        BtnTambah = new widget.Button();
        BtnHapus = new widget.Button();
        BtnEdit = new widget.Button();
        BtnPrint = new widget.Button();
        BtnAll = new widget.Button();
        BtnKeluar = new widget.Button();
        scrollPane1 = new widget.ScrollPane();
        tbPegawai = new widget.Table();
        panelJudul1 = new widget.PanelJudul();
        jLabel1 = new widget.Label();

        DlgInput.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DlgInput.setModal(true);
        DlgInput.setName("DlgInput"); // NOI18N
        DlgInput.setResizable(false);
        DlgInput.setUndecorated(true);

        panelJudul2.setName("panelJudul2"); // NOI18N
        panelJudul2.setPreferredSize(new java.awt.Dimension(522, 40));
        panelJudul2.setLayout(new java.awt.BorderLayout());

        lblKtg.setBackground(new java.awt.Color(0, 100, 0));
        lblKtg.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblKtg.setForeground(new java.awt.Color(202, 202, 142));
        lblKtg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKtg.setText(":: INPUT PRESENSI HARIAN ::         ");
        lblKtg.setIconTextGap(2);
        lblKtg.setName("lblKtg"); // NOI18N
        panelJudul2.add(lblKtg, java.awt.BorderLayout.CENTER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/file-edit-32x32.png"))); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(35, 35));
        panelJudul2.add(jLabel3, java.awt.BorderLayout.LINE_START);

        DlgInput.getContentPane().add(panelJudul2, java.awt.BorderLayout.PAGE_START);

        panel2.setName("panel2"); // NOI18N
        panel2.setPreferredSize(new java.awt.Dimension(440, 25));
        panel2.setLayout(new java.awt.BorderLayout());

        jSeparator3.setBackground(new java.awt.Color(0, 50, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 50, 0));
        jSeparator3.setName("jSeparator3"); // NOI18N
        jSeparator3.setPreferredSize(new java.awt.Dimension(1, 1));
        panel2.add(jSeparator3, java.awt.BorderLayout.PAGE_START);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(202, 202, 142));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(":: Semua field wajib diisi ::");
        jLabel6.setName("jLabel6"); // NOI18N
        panel2.add(jLabel6, java.awt.BorderLayout.CENTER);

        DlgInput.getContentPane().add(panel2, java.awt.BorderLayout.PAGE_END);

        internalFrame2.setName("internalFrame2"); // NOI18N
        internalFrame2.setLayout(null);

        BtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnClose.setMnemonic('C');
        BtnClose.setText("Tutup");
        BtnClose.setToolTipText("Alt+C");
        BtnClose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnClose.setName("BtnClose"); // NOI18N
        BtnClose.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });
        BtnClose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCloseKeyPressed(evt);
            }
        });
        internalFrame2.add(BtnClose);
        BtnClose.setBounds(630, 120, 100, 30);

        BtnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Cancel-2-16x16.png"))); // NOI18N
        BtnBatal.setMnemonic('B');
        BtnBatal.setText("Baru");
        BtnBatal.setToolTipText("Alt+B");
        BtnBatal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnBatal.setName("BtnBatal"); // NOI18N
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        BtnBatal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnBatalKeyPressed(evt);
            }
        });
        internalFrame2.add(BtnBatal);
        BtnBatal.setBounds(125, 120, 100, 30);

        label2.setText("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        label2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label2.setName("label2"); // NOI18N
        internalFrame2.add(label2);
        label2.setBounds(-10, 97, 820, 15);

        label23.setText("NIK :");
        label23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label23.setName("label23"); // NOI18N
        label23.setPreferredSize(new java.awt.Dimension(65, 23));
        internalFrame2.add(label23);
        label23.setBounds(-7, 12, 89, 23);

        Nm.setEditable(false);
        Nm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Nm.setName("Nm"); // NOI18N
        Nm.setPreferredSize(new java.awt.Dimension(207, 23));
        Nm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NmKeyPressed(evt);
            }
        });
        internalFrame2.add(Nm);
        Nm.setBounds(198, 12, 330, 23);

        Cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        Cari.setMnemonic('C');
        Cari.setToolTipText("Alt+C");
        Cari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cari.setName("Cari"); // NOI18N
        Cari.setPreferredSize(new java.awt.Dimension(100, 30));
        internalFrame2.add(Cari);
        Cari.setBounds(530, 12, 25, 23);

        Nik.setEditable(false);
        Nik.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Nik.setName("Nik"); // NOI18N
        Nik.setPreferredSize(new java.awt.Dimension(207, 23));
        Nik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NikKeyPressed(evt);
            }
        });
        internalFrame2.add(Nik);
        Nik.setBounds(85, 12, 110, 23);

        tglMasuk.setDisplayFormat("yyyy-MM-dd");
        tglMasuk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tglMasuk.setName("tglMasuk"); // NOI18N
        tglMasuk.setPreferredSize(new java.awt.Dimension(105, 23));
        internalFrame2.add(tglMasuk);
        tglMasuk.setBounds(85, 42, 110, 23);

        Jam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        Jam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Jam.setName("Jam"); // NOI18N
        internalFrame2.add(Jam);
        Jam.setBounds(198, 42, 50, 23);

        label26.setText("Jam Masuk :");
        label26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label26.setName("label26"); // NOI18N
        label26.setPreferredSize(new java.awt.Dimension(65, 23));
        internalFrame2.add(label26);
        label26.setBounds(-7, 42, 89, 23);

        Menit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));
        Menit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Menit.setName("Menit"); // NOI18N
        internalFrame2.add(Menit);
        Menit.setBounds(251, 42, 50, 23);

        Detik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));
        Detik.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Detik.setName("Detik"); // NOI18N
        internalFrame2.add(Detik);
        Detik.setBounds(304, 42, 50, 23);

        Jam2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        Jam2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Jam2.setName("Jam2"); // NOI18N
        internalFrame2.add(Jam2);
        Jam2.setBounds(560, 42, 50, 23);

        Menit2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));
        Menit2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Menit2.setName("Menit2"); // NOI18N
        internalFrame2.add(Menit2);
        Menit2.setBounds(613, 42, 50, 23);

        Detik2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));
        Detik2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Detik2.setName("Detik2"); // NOI18N
        internalFrame2.add(Detik2);
        Detik2.setBounds(666, 42, 50, 23);

        label28.setText("Jam Pulang :");
        label28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label28.setName("label28"); // NOI18N
        label28.setPreferredSize(new java.awt.Dimension(65, 23));
        internalFrame2.add(label28);
        label28.setBounds(326, 42, 118, 23);

        tglPulang.setDisplayFormat("yyyy-MM-dd");
        tglPulang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tglPulang.setName("tglPulang"); // NOI18N
        tglPulang.setPreferredSize(new java.awt.Dimension(105, 23));
        internalFrame2.add(tglPulang);
        tglPulang.setBounds(447, 42, 110, 23);

        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16i.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setText("Simpan");
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        BtnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSimpanKeyPressed(evt);
            }
        });
        internalFrame2.add(BtnSimpan);
        BtnSimpan.setBounds(13, 120, 100, 30);

        label24.setText("Catatan :");
        label24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label24.setName("label24"); // NOI18N
        label24.setPreferredSize(new java.awt.Dimension(65, 23));
        internalFrame2.add(label24);
        label24.setBounds(-7, 72, 89, 23);

        catatan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        catatan.setName("catatan"); // NOI18N
        internalFrame2.add(catatan);
        catatan.setBounds(85, 72, 630, 23);

        label25.setText("Shift :");
        label25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label25.setName("label25"); // NOI18N
        label25.setPreferredSize(new java.awt.Dimension(65, 23));
        internalFrame2.add(label25);
        label25.setBounds(593, 12, 50, 23);

        Shift.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pagi", "Siang", "Malam", "Midle Pagi1", "Midle Pagi2", "Midle Siang1", "Midle Siang2", "Midle Siang3", "Midle Malam1", "Midle Malam2" }));
        Shift.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Shift.setName("Shift"); // NOI18N
        Shift.setPreferredSize(new java.awt.Dimension(80, 23));
        internalFrame2.add(Shift);
        Shift.setBounds(646, 12, 70, 23);

        jamdatang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jamdatang.setName("jamdatang"); // NOI18N
        jamdatang.setPreferredSize(new java.awt.Dimension(207, 23));
        jamdatang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jamdatangKeyPressed(evt);
            }
        });
        internalFrame2.add(jamdatang);
        jamdatang.setBounds(320, 230, 207, 23);

        jampulang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jampulang.setName("jampulang"); // NOI18N
        jampulang.setPreferredSize(new java.awt.Dimension(207, 23));
        internalFrame2.add(jampulang);
        jampulang.setBounds(220, 230, 207, 23);

        DlgInput.getContentPane().add(internalFrame2, java.awt.BorderLayout.CENTER);

        Idpresensi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Idpresensi.setName("Idpresensi"); // NOI18N
        Idpresensi.setPreferredSize(new java.awt.Dimension(207, 23));
        Idpresensi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IdpresensiKeyPressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);
        setUndecorated(true);

        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(816, 100));
        jPanel2.setLayout(new java.awt.BorderLayout(1, 1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 212, 152)));
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 44));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 9));

        label11.setText("Tahun & Bulan :");
        label11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(90, 23));
        jPanel4.add(label11);

        ThnCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ThnCari.setName("ThnCari"); // NOI18N
        ThnCari.setPreferredSize(new java.awt.Dimension(80, 23));
        jPanel4.add(ThnCari);

        BlnCari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        BlnCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BlnCari.setName("BlnCari"); // NOI18N
        BlnCari.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel4.add(BlnCari);

        label9.setText("Key Word :");
        label9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(70, 23));
        jPanel4.add(label9);

        TCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(250, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        jPanel4.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('1');
        BtnCari.setToolTipText("Alt+1");
        BtnCari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        jPanel4.add(BtnCari);

        label10.setText("Record :");
        label10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label10.setName("label10"); // NOI18N
        label10.setPreferredSize(new java.awt.Dimension(70, 23));
        jPanel4.add(label10);

        LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount.setText("0");
        LCount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LCount.setName("LCount"); // NOI18N
        LCount.setPreferredSize(new java.awt.Dimension(60, 23));
        jPanel4.add(LCount);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 212, 152)));
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 44));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/add-file-16x16.png"))); // NOI18N
        BtnTambah.setMnemonic('T');
        BtnTambah.setText("Tambah");
        BtnTambah.setToolTipText("Alt+T");
        BtnTambah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnTambah.setName("BtnTambah"); // NOI18N
        BtnTambah.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });
        BtnTambah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnTambahKeyPressed(evt);
            }
        });
        jPanel5.add(BtnTambah);

        BtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
        BtnHapus.setMnemonic('H');
        BtnHapus.setText("Hapus");
        BtnHapus.setToolTipText("Alt+H");
        BtnHapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnHapus.setName("BtnHapus"); // NOI18N
        BtnHapus.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        BtnHapus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnHapusKeyPressed(evt);
            }
        });
        jPanel5.add(BtnHapus);

        BtnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/inventaris.png"))); // NOI18N
        BtnEdit.setMnemonic('E');
        BtnEdit.setText("Ganti");
        BtnEdit.setToolTipText("Alt+E");
        BtnEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnEdit.setName("BtnEdit"); // NOI18N
        BtnEdit.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });
        BtnEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnEditKeyPressed(evt);
            }
        });
        jPanel5.add(BtnEdit);

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('P');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+P");
        BtnPrint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        jPanel5.add(BtnPrint);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('2');
        BtnAll.setText("Semua");
        BtnAll.setToolTipText("Alt+2");
        BtnAll.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        jPanel5.add(BtnAll);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        jPanel5.add(BtnKeluar);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        internalFrame1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        scrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 212, 152)));
        scrollPane1.setName("scrollPane1"); // NOI18N
        scrollPane1.setOpaque(true);

        tbPegawai.setAutoCreateRowSorter(true);
        tbPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPegawai.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbPegawai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbPegawai.setName("tbPegawai"); // NOI18N
        tbPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPegawaiMouseClicked(evt);
            }
        });
        tbPegawai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbPegawaiKeyPressed(evt);
            }
        });
        scrollPane1.setViewportView(tbPegawai);

        internalFrame1.add(scrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        panelJudul1.setName("panelJudul1"); // NOI18N
        panelJudul1.setPreferredSize(new java.awt.Dimension(163, 28));
        panelJudul1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 100, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(202, 202, 142));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(":: DATA REKAP BULANAN ::");
        jLabel1.setIconTextGap(2);
        jLabel1.setName("jLabel1"); // NOI18N
        panelJudul1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelJudul1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnCariActionPerformed(null);
        }else{Valid.pindah(evt, BtnKeluar, BtnCari);}
}//GEN-LAST:event_TCariKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        String say=" rekap_presensi.jam_datang like '%"+ThnCari.getSelectedItem()+"-"+BlnCari.getSelectedItem()+"%'   ";
        prosesCari("select  pegawai.id, "+
                "pegawai.nik, "+
                "pegawai.nama, "+
                "rekap_presensi.shift, "+
                "rekap_presensi.jam_datang, "+
                "rekap_presensi.jam_pulang, "+
                "rekap_presensi.status, "+
                "rekap_presensi.keterlambatan, "+
                "rekap_presensi.durasi, "+
                "rekap_presensi.keterangan "+
                " from pegawai inner join rekap_presensi on pegawai.id=rekap_presensi.id where "+
                   " pegawai.nik like '%"+TCari.getText().trim()+"%' and "+say+
                   "or pegawai.nama like '%"+TCari.getText().trim()+"%' and "+say+                   
                   "or rekap_presensi.shift like '%"+TCari.getText().trim()+"%' and "+say+
                   "or rekap_presensi.status like '%"+TCari.getText().trim()+"%' and "+say+
                   "or rekap_presensi.keterlambatan like '%"+TCari.getText().trim()+"%' and "+say+
                   "or rekap_presensi.jam_datang like '%"+TCari.getText().trim()+"%' and "+say+
                   "or rekap_presensi.jam_pulang like '%"+TCari.getText().trim()+"%' and "+say+" order by pegawai.nama ");
}//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnCariActionPerformed(null);
        }else{
            Valid.pindah(evt, TCari, BtnAll);
        }
}//GEN-LAST:event_BtnCariKeyPressed

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
        emptTeks();
        DlgInput.dispose();
}//GEN-LAST:event_BtnCloseActionPerformed

    private void BtnCloseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCloseKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            DlgInput.dispose();
        }else{Valid.pindah(evt,BtnBatal,BtnClose);}
}//GEN-LAST:event_BtnCloseKeyPressed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        if(tglMasuk.isEditable()==true){
            emptTeks();
        }else if(tglMasuk.isEditable()==false){
            emptTeks();
            DlgInput.dispose();
        }
}//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnBatalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnBatalKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            emptTeks();
        }else{Valid.pindah(evt, BtnSimpan, BtnClose);}
}//GEN-LAST:event_BtnBatalKeyPressed

private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
            Jam.requestFocus();
            Cari.setEnabled(true);
            tglMasuk.setEnabled(true);
            Jam.setEnabled(true);
            Menit.setEnabled(true);
            Detik.setEnabled(true);
            lblKtg.setText(":: PRESENSI MASUK ::         ");
            //LabelKon.setVisible(true);
            DlgInput.setLocationRelativeTo(null);
            DlgInput.setVisible(true);
        
}//GEN-LAST:event_BtnTambahActionPerformed

private void BtnTambahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnTambahKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnTambahActionPerformed(null);
        }else{
            Valid.pindah(evt, TCari, BtnEdit);
        }
}//GEN-LAST:event_BtnTambahKeyPressed

private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, Tabel kosong. Tidak ada data yang bisa Anda edit..!!!!");
            BtnTambah.requestFocus();
        }else if(Nm.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Pilih dulu data yang akan Anda edit dengan menklik data pada tabel...!!!");
            tbPegawai.requestFocus();
        }else if(! Nm.getText().trim().equals("")){
            lblKtg.setText(":: PRESENSI PULANG ::         ");
            Cari.setEnabled(false);            
            tglMasuk.setEnabled(false);
            Jam.setEnabled(false);
            Menit.setEnabled(false);
            Detik.setEnabled(false);
            Nm.requestFocus();
            //LabelKon.setVisible(true);
            DlgInput.setLocationRelativeTo(null);
            DlgInput.setVisible(true);
        }
}//GEN-LAST:event_BtnEditActionPerformed

private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        TCari.setText("");
        tampil("");
}//GEN-LAST:event_BtnAllActionPerformed

private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnAllActionPerformed(null);
        }else{
            Valid.pindah(evt, BtnEdit, BtnKeluar);
        }
}//GEN-LAST:event_BtnAllKeyPressed

private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
            dispose();  
}//GEN-LAST:event_BtnKeluarActionPerformed

private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            dispose();  
        }else{Valid.pindah(evt,BtnAll,TCari);}
}//GEN-LAST:event_BtnKeluarKeyPressed

private void BtnEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnEditKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnEditActionPerformed(null);
        }else{
            Valid.pindah(evt, BtnTambah, BtnAll);
        }
}//GEN-LAST:event_BtnEditKeyPressed

private void IdpresensiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdpresensiKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_IdpresensiKeyPressed

private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        if(Nm.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Pilih dulu data yang akan Anda hapus dengan menklik data pada tabel...!!!");
            tbPegawai.requestFocus();
        }else{
            Valid.hapusTable(tabMode,Idpresensi,"rekap_presensi","jam_datang='"+tgl[no]+"' and  id");
            tampil("");
            emptTeks();
        }
}//GEN-LAST:event_BtnHapusActionPerformed

private void BtnHapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnHapusKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnHapusActionPerformed(null);
        }else{
            Valid.pindah(evt, BtnTambah, BtnEdit);
        }
}//GEN-LAST:event_BtnHapusKeyPressed

private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if(! TCari.getText().trim().equals("")){
            BtnCariActionPerformed(evt);
        }
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, data sudah habis. Tidak ada data yang bisa anda print...!!!!");
            BtnBatal.requestFocus();
        }else if(tabMode.getRowCount()!=0){
            if(TCari.getText().trim().equals("")){
                Valid.MyReport("rptHarian.jrxml","report","::[ Rekap Harian ]::","select  pegawai.id, "+
                "pegawai.nik, "+
                "pegawai.nama, "+
                "rekap_presensi.shift, "+
                "rekap_presensi.jam_datang, "+
                "rekap_presensi.jam_pulang, "+
                "rekap_presensi.status, "+
                "rekap_presensi.keterlambatan, "+
                "rekap_presensi.durasi, "+
                "rekap_presensi.keterangan "+
                " from pegawai inner join rekap_presensi on pegawai.id=rekap_presensi.id where rekap_presensi.jam_datang like '%"+ThnCari.getSelectedItem()+"-"+BlnCari.getSelectedItem()+"%' order by pegawai.nama");
            }else if(! TCari.getText().trim().equals("")){
                String say=" rekap_presensi.jam_datang like '%"+ThnCari.getSelectedItem()+"-"+BlnCari.getSelectedItem()+"%' ";
                Valid.MyReport("rptHarian.jrxml","report","::[ Rekap Harian ]::","select  pegawai.id, "+
                "pegawai.nik, "+
                "pegawai.nama, "+
                "rekap_presensi.shift, "+
                "rekap_presensi.jam_datang, "+
                "rekap_presensi.jam_pulang, "+
                "rekap_presensi.status, "+
                "rekap_presensi.keterlambatan, "+
                "rekap_presensi.durasi, "+
                "rekap_presensi.keterangan "+
                " from pegawai inner join rekap_presensi on pegawai.id=rekap_presensi.id where "+
                   " pegawai.nik like '%"+TCari.getText().trim()+"%' and "+say+
                   "or pegawai.nama like '%"+TCari.getText().trim()+"%' and "+say+                   
                   "or rekap_presensi.shift like '%"+TCari.getText().trim()+"%' and "+say+
                   "or rekap_presensi.status like '%"+TCari.getText().trim()+"%' and "+say+
                   "or rekap_presensi.keterlambatan like '%"+TCari.getText().trim()+"%' and "+say+
                   "or rekap_presensi.jam_datang like '%"+TCari.getText().trim()+"%' and "+say+
                   "or rekap_presensi.jam_pulang like '%"+TCari.getText().trim()+"%' and "+say+" order by pegawai.nama  ");
            }
        }
        this.setCursor(Cursor.getDefaultCursor());
}//GEN-LAST:event_BtnPrintActionPerformed

private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPrintKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnPrintActionPerformed(null);
        }else{
            Valid.pindah(evt,BtnEdit,BtnAll);
        }
}//GEN-LAST:event_BtnPrintKeyPressed

private void tbPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPegawaiMouseClicked
   if(tabMode.getRowCount()!=0){
            try {
                getData();
            } catch (java.lang.NullPointerException e) {
            }
   }
}//GEN-LAST:event_tbPegawaiMouseClicked

private void tbPegawaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbPegawaiKeyPressed
   if(tabMode.getRowCount()!=0){
            if((evt.getKeyCode()==KeyEvent.VK_ENTER)||(evt.getKeyCode()==KeyEvent.VK_UP)||(evt.getKeyCode()==KeyEvent.VK_DOWN)){
                try {
                    getData();
                } catch (java.lang.NullPointerException e) {
                }
            }
    }
}//GEN-LAST:event_tbPegawaiKeyPressed

    private void NmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NmKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NmKeyPressed

    private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
        bar.emptTeks();
        bar.tampil("");
        bar.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
        bar.setLocationRelativeTo(internalFrame1);
        bar.setVisible(true);
    }//GEN-LAST:event_CariActionPerformed

    private void NikKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NikKeyPressed
// TODO add your handling code here:
    }//GEN-LAST:event_NikKeyPressed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        if (Nik.getText().trim().equals("")) {
            Valid.textKosong(Nik, "ID");
        } else {
            Sequel.cariIsi("select jam_jaga.jam_masuk from jam_jaga inner join pegawai on pegawai.departemen=jam_jaga.dep_id "+
                                " where jam_jaga.shift='"+Shift.getSelectedItem().toString()+"' and pegawai.id='"+Idpresensi.getText()+"'", jamdatang);
            Sequel.cariIsi("select jam_jaga.jam_pulang from jam_jaga inner join pegawai on pegawai.departemen=jam_jaga.dep_id "+
                                                       " where jam_jaga.shift='"+Shift.getSelectedItem().toString()+"' and pegawai.id='"+Idpresensi.getText()+"'", jampulang);
            String jam="now()";
            if(!jamdatang.getText().equals("")){
                  jam="'"+tglMasuk.getSelectedItem()+" "+jamdatang.getText()+"'";
            }
            String jam2="now()";
            if(!jampulang.getText().equals("")){
                  jam2="'"+tglPulang.getSelectedItem()+" "+jampulang.getText()+"'";
            }
            if (tglMasuk.isEnabled()==true) {
                //----------------simpan-------------------------------------------
                Sequel.menyimpan("rekap_presensi", "'" + Idpresensi.getText()
                        + "','"+Shift.getSelectedItem()+"','" + tglMasuk.getSelectedItem() + " " + Jam.getSelectedItem() + ":" + Menit.getSelectedItem() + ":" + Detik.getSelectedItem()
                        + "','" + tglPulang.getSelectedItem() + " " + Jam2.getSelectedItem() + ":" + Menit2.getSelectedItem() + ":" + Detik2.getSelectedItem()
                        + "',if(TIME_TO_SEC('"+tglMasuk.getSelectedItem()+" "+Jam.getSelectedItem()+"-"+Menit.getSelectedItem()+"-"+Detik.getSelectedItem()+"')-TIME_TO_SEC("+jam+")>600,'Terlambat','Tepat Waktu'),"
                        +"if(TIME_TO_SEC('"+tglMasuk.getSelectedItem()+" "+Jam.getSelectedItem()+"-"+Menit.getSelectedItem()+"-"+Detik.getSelectedItem()+"')-TIME_TO_SEC("+jam+")>600,SEC_TO_TIME(TIME_TO_SEC('"+tglMasuk.getSelectedItem()+" "+Jam.getSelectedItem()+"-"+Menit.getSelectedItem()+"-"+Detik.getSelectedItem()+"')-TIME_TO_SEC("+jam+")),''),"
                        + "(SEC_TO_TIME(unix_timestamp('" + tglPulang.getSelectedItem().toString() + " " + Jam2.getSelectedItem() + ":" + Menit2.getSelectedItem() + ":" + Detik2.getSelectedItem()
                        + "') - unix_timestamp('" +tglMasuk.getSelectedItem().toString() + " " + Jam.getSelectedItem() + ":" + Menit.getSelectedItem() + ":" + Detik.getSelectedItem() + "'))),'"+catatan.getText()+"',''", "ID/Presensi");

            } else if (tglMasuk.isEnabled()==false) {
                Valid.editTable(tabMode, "rekap_presensi", "jam_datang='" + tglMasuk.getSelectedItem() + " " + Jam.getSelectedItem() + ":" + Menit.getSelectedItem() + ":" + Detik.getSelectedItem()
                        + "' and id", Idpresensi,"jam_pulang='" + tglPulang.getSelectedItem() + " " + Jam2.getSelectedItem() + ":" + Menit2.getSelectedItem() + ":" + Detik2.getSelectedItem()
                        + "',durasi=(SEC_TO_TIME(unix_timestamp('" + tglPulang.getSelectedItem().toString() + " " + Jam2.getSelectedItem() + ":" + Menit2.getSelectedItem() + ":" + Detik2.getSelectedItem()
                        + "') - unix_timestamp('" + tglMasuk.getSelectedItem().toString() + " " + Jam.getSelectedItem() + ":" + Menit.getSelectedItem() + ":" + Detik.getSelectedItem() + "'))),"
                        +"keterangan='"+catatan.getText()+"',"
                        +"shift='"+Shift.getSelectedItem()+"',"
                        +"status=if(TIME_TO_SEC('"+tglMasuk.getSelectedItem()+" "+Jam.getSelectedItem()+"-"+Menit.getSelectedItem()+"-"+Detik.getSelectedItem()+"')-TIME_TO_SEC("+jam+")>600,'Terlambat','Tepat Waktu'),"
                        +"keterlambatan=if(TIME_TO_SEC('"+tglMasuk.getSelectedItem()+" "+Jam.getSelectedItem()+"-"+Menit.getSelectedItem()+"-"+Detik.getSelectedItem()+"')-TIME_TO_SEC("+jam+")>600,SEC_TO_TIME(TIME_TO_SEC('"+tglMasuk.getSelectedItem()+" "+Jam.getSelectedItem()+"-"+Menit.getSelectedItem()+"-"+Detik.getSelectedItem()+"')-TIME_TO_SEC("+jam+")),'')");
                DlgInput.dispose();
            }
            tampil("");
            emptTeks();
        }
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSimpanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnSimpanActionPerformed(null);
        } else {
            //  Valid.pindah(evt,Pas,BtnBatal);
        }
    }//GEN-LAST:event_BtnSimpanKeyPressed

private void jamdatangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jamdatangKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_jamdatangKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgBulanan dialog = new DlgBulanan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.ComboBox BlnCari;
    private widget.Button BtnAll;
    private widget.Button BtnBatal;
    private widget.Button BtnCari;
    private widget.Button BtnClose;
    private widget.Button BtnEdit;
    private widget.Button BtnHapus;
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.Button BtnSimpan;
    private widget.Button BtnTambah;
    private widget.Button Cari;
    private widget.ComboBox Detik;
    private widget.ComboBox Detik2;
    private javax.swing.JDialog DlgInput;
    private widget.TextBox Idpresensi;
    private widget.ComboBox Jam;
    private widget.ComboBox Jam2;
    private widget.Label LCount;
    private widget.ComboBox Menit;
    private widget.ComboBox Menit2;
    private widget.TextBox Nik;
    private widget.TextBox Nm;
    private widget.ComboBox Shift;
    private widget.TextBox TCari;
    private widget.ComboBox ThnCari;
    private widget.TextBox catatan;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame2;
    private widget.Label jLabel1;
    private widget.Label jLabel3;
    private widget.Label jLabel6;
    private widget.panelisi jPanel2;
    private widget.panelisi jPanel4;
    private widget.panelisi jPanel5;
    private javax.swing.JSeparator jSeparator3;
    private widget.TextBox jamdatang;
    private widget.TextBox jampulang;
    private widget.Label label10;
    private widget.Label label11;
    private widget.Label label2;
    private widget.Label label23;
    private widget.Label label24;
    private widget.Label label25;
    private widget.Label label26;
    private widget.Label label28;
    private widget.Label label9;
    private widget.Label lblKtg;
    private widget.Panel panel2;
    private widget.PanelJudul panelJudul1;
    private widget.PanelJudul panelJudul2;
    private widget.ScrollPane scrollPane1;
    private widget.Table tbPegawai;
    private widget.Tanggal tglMasuk;
    private widget.Tanggal tglPulang;
    // End of variables declaration//GEN-END:variables

    public void tampil(String key) {
        String sql="select  pegawai.id, "+
                "pegawai.nik, "+
                "pegawai.nama, "+
                "rekap_presensi.shift, "+
                "rekap_presensi.jam_datang, "+
                "rekap_presensi.jam_pulang, "+
                "rekap_presensi.status, "+
                "rekap_presensi.keterlambatan, "+
                "rekap_presensi.durasi, "+
                "rekap_presensi.keterangan "+
                " from pegawai inner join rekap_presensi on pegawai.id=rekap_presensi.id where rekap_presensi.jam_datang like '%"+ThnCari.getSelectedItem()+"-"+BlnCari.getSelectedItem()+"%' order by pegawai.nama,rekap_presensi.jam_datang";
        prosesCari(sql);
    }

    private void prosesCari(String sql) {
        Valid.tabelKosong(tabMode);
        try{
            java.sql.Statement stat=connect.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            rs.last();
            
            id=new String[rs.getRow()];
            tgl=new String[rs.getRow()];
            
            rs.beforeFirst();
            
            int i=0;
            
            while(rs.next()){
                String[] data={rs.getString(2),
                               rs.getString(3),
                               rs.getString(4),
                               rs.getString(5),
                               rs.getString(6),
                               rs.getString(7),
                               rs.getString(8),
                               rs.getString(9),
                               rs.getString(10)};
                tabMode.addRow(data);
                id[i]=rs.getString(1);
                tgl[i]=rs.getString(5);
                i++;
             }
            rs.close();
            stat.close();
        }catch(SQLException e){
            System.out.println("Error : "+e);
        }
        LCount.setText(""+tabMode.getRowCount());

    }

    public void emptTeks() {
        Idpresensi.setText("");        
        Jam.setSelectedItem("00");
        Jam2.setSelectedItem("00");
        Menit.setSelectedItem("00");
        Menit2.setSelectedItem("00");
        Detik.setSelectedItem("00");
        Detik2.setSelectedItem("00");
        catatan.setText("");
    }
    
    private void isBar(){
        Sequel.cariIsi("select pegawai.nik from pegawai  where pegawai.id='"+Idpresensi.getText()+"'", Nik);
        Sequel.cariIsi("select pegawai.nama from pegawai  where pegawai.id='"+Idpresensi.getText()+"'", Nm);
    }
    
    private void getData() {
        int row=tbPegawai.getSelectedRow();
        if(row!= -1){
            no=row;
            Idpresensi.setText(id[no]);            
            Shift.setSelectedItem(tabMode.getValueAt(row,2).toString());            
            if(!tabMode.getValueAt(row,3).toString().equals("")){
                Jam.setSelectedItem(tabMode.getValueAt(row,3).toString().substring(11,13));
                Menit.setSelectedItem(tabMode.getValueAt(row,3).toString().substring(14,16));
                Detik.setSelectedItem(tabMode.getValueAt(row,3).toString().substring(17,19));
            }else if(tabMode.getValueAt(row,3).toString().equals("")){
                Jam.setSelectedItem("00");
                Menit.setSelectedItem("00");
                Detik.setSelectedItem("00");
            }            
                        
            if(!tabMode.getValueAt(row,4).toString().equals("")){
                Jam2.setSelectedItem(tabMode.getValueAt(row,4).toString().substring(11,13));
                Menit2.setSelectedItem(tabMode.getValueAt(row,4).toString().substring(14,16));
                Detik2.setSelectedItem(tabMode.getValueAt(row,4).toString().substring(17,19));
            }else if(tabMode.getValueAt(row,4).toString().equals("")){
                Jam2.setSelectedItem("00");
                Menit2.setSelectedItem("00");
                Detik2.setSelectedItem("00");
            }
            catatan.setText(tabMode.getValueAt(row,8).toString());
            
            try {
                tglMasuk.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(
                                tabMode.getValueAt(row,3).toString().substring(0,4)+"-"+
                                tabMode.getValueAt(row,3).toString().substring(5,7)+"-"+
                                tabMode.getValueAt(row,3).toString().substring(8,10)));
            } catch (ParseException ex) {
                Logger.getLogger(DlgHarian.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                tglPulang.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(
                                tabMode.getValueAt(row,4).toString().substring(0,4)+"-"+
                                tabMode.getValueAt(row,4).toString().substring(5,7)+"-"+
                                tabMode.getValueAt(row,4).toString().substring(8,10)));
            } catch (ParseException ex) {
                Logger.getLogger(DlgHarian.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
    }
    
    private  void loadTahun(){
        Valid.LoadTahun(ThnCari);
    }

 
}
