/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgKamar.java
 *
 * Created on May 23, 2010, 12:07:21 AM
 */

package khanzahms;

import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.var;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author dosen
 */
public final class DlgKamar extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();

    /** Creates new form DlgKamar
     * @param parent
     * @param modal */
    public DlgKamar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocation(10,2);
        setSize(628,674);

        Object[] row={"Nomer Bad",
                      "Kode Kamar",
                      "Nama Kamar",
                      "Kelas",
                      "Tarif Kamar",
                      "Status Kamar"};
        tabMode=new DefaultTableModel(null,row){
              @Override public boolean isCellEditable(int rowIndex, int colIndex){return false;}
        };
        tbKamar.setModel(tabMode);

        //tbKamar.setDefaultRenderer(Object.class, new WarnaTable(panelJudul.getBackground(),tbKamar.getBackground()));
        tbKamar.setPreferredScrollableViewportSize(new Dimension(500,500));
        tbKamar.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (int i = 0; i < 6; i++) {
            TableColumn column = tbKamar.getColumnModel().getColumn(i);
            if(i==0){
                column.setPreferredWidth(100);
            }else if(i==1){
                column.setPreferredWidth(100);
            }else if(i==2){
                column.setPreferredWidth(300);
            }else if(i==3){
                column.setPreferredWidth(150);
            }else if(i==4){
                column.setPreferredWidth(150);
            }else if(i==5){
                 column.setPreferredWidth(150);
            }
        }
        tbKamar.setDefaultRenderer(Object.class, new WarnaTable());

        TKd.setDocument(new batasInput((byte)15).getKata(TKd));
        TTarif.setDocument(new batasInput((byte)16).getOnlyAngka(TTarif));
        kd_bangsal.setDocument(new batasInput((byte)5).getKata(kd_bangsal));
        kdbangsalcari.setDocument(new batasInput((byte)5).getKata(kdbangsalcari));
        Kelas.setDocument(new batasInput((byte)15).getKata(Kelas));
        TCari.setDocument(new batasInput((byte)100).getKata(TCari));

        panelCari.setVisible(false);
        posisi();
        
        bangsal.getTable().addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) { 
                load();
                if(pilihan==1){
                    kd_bangsal.setText(bangsal.getTextField().getText());
                    Sequel.cariIsi("select bangsal.nm_bangsal from bangsal where bangsal.kd_bangsal=?", TBangsal,kd_bangsal.getText());
                }else if(pilihan==2){
                    kdbangsalcari.setText(bangsal.getTextField().getText());
                    Sequel.cariIsi("select bangsal.nm_bangsal from bangsal where bangsal.kd_bangsal=?",BangsalCari,kdbangsalcari.getText());
                    tampil();
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {}
            @Override
            public void mouseReleased(MouseEvent e) {}
            @Override
            public void mouseEntered(MouseEvent e) {}
            @Override
            public void mouseExited(MouseEvent e) {}
        });
        
        //bangsal.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);
        //bangsal.setModalityType(ModalityType.APPLICATION_MODAL);
    }
    
    public DlgCariBangsal bangsal=new DlgCariBangsal(null,false);
    private int pilihan=0;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbKamar = new widget.Table();
        PanelCariUtama = new javax.swing.JPanel();
        panelGlass5 = new widget.panelisi();
        BtnSimpan = new widget.Button();
        BtnBatal = new widget.Button();
        BtnHapus = new widget.Button();
        BtnEdit = new widget.Button();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();
        panelGlass6 = new widget.panelisi();
        jLabel6 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnAll = new widget.Button();
        jLabel7 = new widget.Label();
        LCount = new widget.Label();
        panelCariKategori = new javax.swing.JPanel();
        panelCari = new widget.panelisi();
        jLabel13 = new widget.Label();
        kdbangsalcari = new widget.TextBox();
        BangsalCari = new widget.TextBox();
        BtnSeek1 = new widget.Button();
        jLabel11 = new widget.Label();
        CmbCrIsi = new widget.ComboBox();
        ChkCari = new widget.CekBox();
        panelGlass4 = new widget.panelisi();
        jLabel3 = new widget.Label();
        jLabel4 = new widget.Label();
        TKd = new widget.TextBox();
        TBangsal = new widget.TextBox();
        jLabel8 = new widget.Label();
        TTarif = new widget.TextBox();
        jLabel9 = new widget.Label();
        CmbStatus = new widget.ComboBox();
        BtnSeek = new widget.Button();
        kd_bangsal = new widget.TextBox();
        jLabel5 = new widget.Label();
        Kelas = new widget.TextBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Data Nomor Kamar ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 70, 40))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbKamar.setAutoCreateRowSorter(true);
        tbKamar.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbKamar.setName("tbKamar"); // NOI18N
        tbKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKamarMouseClicked(evt);
            }
        });
        tbKamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbKamarKeyPressed(evt);
            }
        });
        Scroll.setViewportView(tbKamar);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        PanelCariUtama.setName("PanelCariUtama"); // NOI18N
        PanelCariUtama.setOpaque(false);
        PanelCariUtama.setPreferredSize(new java.awt.Dimension(100, 162));
        PanelCariUtama.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass5.setName("panelGlass5"); // NOI18N
        panelGlass5.setPreferredSize(new java.awt.Dimension(55, 55));
        panelGlass5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setText("Simpan");
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        BtnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSimpanKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnSimpan);

        BtnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Cancel-2-16x16.png"))); // NOI18N
        BtnBatal.setMnemonic('B');
        BtnBatal.setText("Baru");
        BtnBatal.setToolTipText("Alt+B");
        BtnBatal.setName("BtnBatal"); // NOI18N
        BtnBatal.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        BtnBatal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnBatalKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnBatal);

        BtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
        BtnHapus.setMnemonic('H');
        BtnHapus.setText("Hapus");
        BtnHapus.setToolTipText("Alt+H");
        BtnHapus.setName("BtnHapus"); // NOI18N
        BtnHapus.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        BtnHapus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnHapusKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnHapus);

        BtnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/inventaris.png"))); // NOI18N
        BtnEdit.setMnemonic('G');
        BtnEdit.setText("Ganti");
        BtnEdit.setToolTipText("Alt+G");
        BtnEdit.setName("BtnEdit"); // NOI18N
        BtnEdit.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });
        BtnEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnEditKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnEdit);

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnPrint);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnKeluar);

        PanelCariUtama.add(panelGlass5, java.awt.BorderLayout.PAGE_END);

        panelGlass6.setName("panelGlass6"); // NOI18N
        panelGlass6.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel6.setText("Key Word :");
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass6.add(jLabel6);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(350, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TCariKeyTyped(evt);
            }
        });
        panelGlass6.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('3');
        BtnCari.setToolTipText("Alt+3");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass6.add(BtnCari);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('4');
        BtnAll.setToolTipText("Alt+4");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelGlass6.add(BtnAll);

        jLabel7.setText("Record :");
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(65, 23));
        panelGlass6.add(jLabel7);

        LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount.setText("0");
        LCount.setName("LCount"); // NOI18N
        LCount.setPreferredSize(new java.awt.Dimension(50, 23));
        panelGlass6.add(LCount);

        PanelCariUtama.add(panelGlass6, java.awt.BorderLayout.CENTER);

        panelCariKategori.setName("panelCariKategori"); // NOI18N
        panelCariKategori.setOpaque(false);
        panelCariKategori.setPreferredSize(new java.awt.Dimension(100, 62));
        panelCariKategori.setLayout(new java.awt.BorderLayout(1, 1));

        panelCari.setName("panelCari"); // NOI18N
        panelCari.setPreferredSize(new java.awt.Dimension(44, 44));
        panelCari.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        jLabel13.setText("Kamar :");
        jLabel13.setName("jLabel13"); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(70, 23));
        panelCari.add(jLabel13);

        kdbangsalcari.setEditable(false);
        kdbangsalcari.setHighlighter(null);
        kdbangsalcari.setName("kdbangsalcari"); // NOI18N
        kdbangsalcari.setPreferredSize(new java.awt.Dimension(90, 23));
        kdbangsalcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kdbangsalcariKeyPressed(evt);
            }
        });
        panelCari.add(kdbangsalcari);

        BangsalCari.setEditable(false);
        BangsalCari.setName("BangsalCari"); // NOI18N
        BangsalCari.setPreferredSize(new java.awt.Dimension(200, 23));
        panelCari.add(BangsalCari);

        BtnSeek1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        BtnSeek1.setMnemonic('2');
        BtnSeek1.setToolTipText("Alt+2");
        BtnSeek1.setName("BtnSeek1"); // NOI18N
        BtnSeek1.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnSeek1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeek1ActionPerformed(evt);
            }
        });
        BtnSeek1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSeek1KeyPressed(evt);
            }
        });
        panelCari.add(BtnSeek1);

        jLabel11.setText("Stts.Kamar :");
        jLabel11.setName("jLabel11"); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(85, 23));
        panelCari.add(jLabel11);

        CmbCrIsi.setForeground(new java.awt.Color(153, 0, 51));
        CmbCrIsi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "ISI", "KOSONG" }));
        CmbCrIsi.setName("CmbCrIsi"); // NOI18N
        CmbCrIsi.setOpaque(false);
        CmbCrIsi.setPreferredSize(new java.awt.Dimension(95, 23));
        CmbCrIsi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CmbCrIsiItemStateChanged(evt);
            }
        });
        CmbCrIsi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CmbCrIsiKeyPressed(evt);
            }
        });
        panelCari.add(CmbCrIsi);

        panelCariKategori.add(panelCari, java.awt.BorderLayout.CENTER);

        ChkCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/145.png"))); // NOI18N
        ChkCari.setMnemonic('I');
        ChkCari.setText("  .: Pencarian Data  :: ============================================================= ::");
        ChkCari.setToolTipText("Alt+I");
        ChkCari.setBorderPainted(true);
        ChkCari.setBorderPaintedFlat(true);
        ChkCari.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ChkCari.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ChkCari.setIconTextGap(2);
        ChkCari.setName("ChkCari"); // NOI18N
        ChkCari.setPreferredSize(new java.awt.Dimension(632, 22));
        ChkCari.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/145.png"))); // NOI18N
        ChkCari.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkCari.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkCariActionPerformed(evt);
            }
        });
        panelCariKategori.add(ChkCari, java.awt.BorderLayout.PAGE_START);

        PanelCariUtama.add(panelCariKategori, java.awt.BorderLayout.PAGE_START);

        internalFrame1.add(PanelCariUtama, java.awt.BorderLayout.PAGE_END);

        panelGlass4.setName("panelGlass4"); // NOI18N
        panelGlass4.setPreferredSize(new java.awt.Dimension(0, 77));
        panelGlass4.setLayout(null);

        jLabel3.setText("Nomer Bad :");
        jLabel3.setName("jLabel3"); // NOI18N
        panelGlass4.add(jLabel3);
        jLabel3.setBounds(0, 12, 82, 23);

        jLabel4.setText("Kamar :");
        jLabel4.setName("jLabel4"); // NOI18N
        panelGlass4.add(jLabel4);
        jLabel4.setBounds(0, 42, 82, 23);

        TKd.setHighlighter(null);
        TKd.setName("TKd"); // NOI18N
        TKd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TKdKeyPressed(evt);
            }
        });
        panelGlass4.add(TKd);
        TKd.setBounds(86, 12, 100, 23);

        TBangsal.setEditable(false);
        TBangsal.setName("TBangsal"); // NOI18N
        TBangsal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TBangsalKeyPressed(evt);
            }
        });
        panelGlass4.add(TBangsal);
        TBangsal.setBounds(158, 42, 250, 23);

        jLabel8.setText("Tarif/Hari : Rp.");
        jLabel8.setName("jLabel8"); // NOI18N
        panelGlass4.add(jLabel8);
        jLabel8.setBounds(184, 12, 110, 23);

        TTarif.setHighlighter(null);
        TTarif.setName("TTarif"); // NOI18N
        TTarif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TTarifKeyPressed(evt);
            }
        });
        panelGlass4.add(TTarif);
        TTarif.setBounds(299, 12, 140, 23);

        jLabel9.setText("Stts.Kamar :");
        jLabel9.setName("jLabel9"); // NOI18N
        panelGlass4.add(jLabel9);
        jLabel9.setBounds(440, 12, 90, 23);

        CmbStatus.setForeground(new java.awt.Color(153, 0, 51));
        CmbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ISI", "KOSONG" }));
        CmbStatus.setName("CmbStatus"); // NOI18N
        CmbStatus.setOpaque(false);
        CmbStatus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CmbStatusKeyPressed(evt);
            }
        });
        panelGlass4.add(CmbStatus);
        CmbStatus.setBounds(534, 12, 85, 23);

        BtnSeek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        BtnSeek.setMnemonic('1');
        BtnSeek.setToolTipText("Alt+1");
        BtnSeek.setName("BtnSeek"); // NOI18N
        BtnSeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeekActionPerformed(evt);
            }
        });
        BtnSeek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSeekKeyPressed(evt);
            }
        });
        panelGlass4.add(BtnSeek);
        BtnSeek.setBounds(411, 42, 28, 23);

        kd_bangsal.setHighlighter(null);
        kd_bangsal.setName("kd_bangsal"); // NOI18N
        kd_bangsal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kd_bangsalKeyPressed(evt);
            }
        });
        panelGlass4.add(kd_bangsal);
        kd_bangsal.setBounds(86, 42, 70, 23);

        jLabel5.setText("Kelas :");
        jLabel5.setName("jLabel5"); // NOI18N
        panelGlass4.add(jLabel5);
        jLabel5.setBounds(440, 42, 90, 23);

        Kelas.setHighlighter(null);
        Kelas.setName("Kelas"); // NOI18N
        Kelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KelasKeyPressed(evt);
            }
        });
        panelGlass4.add(Kelas);
        Kelas.setBounds(534, 42, 85, 23);

        internalFrame1.add(panelGlass4, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TKdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
        Valid.pindah(evt,TCari,kd_bangsal);
}//GEN-LAST:event_TKdKeyPressed

    private void TBangsalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TBangsalKeyPressed
        Valid.pindah(evt,TKd,BtnSimpan);
}//GEN-LAST:event_TBangsalKeyPressed

    private void TTarifKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TTarifKeyPressed
        Valid.pindah(evt,kd_bangsal,CmbStatus);
}//GEN-LAST:event_TTarifKeyPressed

    private void CmbStatusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CmbStatusKeyPressed
        Valid.pindah(evt,TTarif,Kelas);
}//GEN-LAST:event_CmbStatusKeyPressed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        if(TKd.getText().trim().equals("")){
            Valid.textKosong(TKd,"Kode Kamar");
        }else if(TBangsal.getText().trim().equals("")){
            Valid.textKosong(TBangsal,"Bangsal");
        }else if(TTarif.getText().trim().equals("")){
            Valid.textKosong(TTarif,"Tarif");
        }else if(Kelas.getText().trim().equals("")){
            Valid.textKosong(Kelas,"Kelas");
        }else{
            Sequel.menyimpan("kamar","'"+TKd.getText()+"','"+
                    kd_bangsal.getText()+"','"+
                    TTarif.getText()+"','"+
                    CmbStatus.getSelectedItem()+"','"+Kelas.getText()+"'","Nomer Bad/Kamar");
            tampil();
            emptTeks();
        }
}//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSimpanKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnSimpanActionPerformed(null);
        }else{
            Valid.pindah(evt,Kelas,BtnBatal);
        }
}//GEN-LAST:event_BtnSimpanKeyPressed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        emptTeks();
}//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnBatalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnBatalKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            emptTeks();
        }else{Valid.pindah(evt, BtnSimpan, BtnHapus);}
}//GEN-LAST:event_BtnBatalKeyPressed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        Valid.hapusTable(tabMode,TKd,"kamar","kd_kamar");
        tampil();
        emptTeks();
}//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnHapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnHapusKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnHapusActionPerformed(null);
        }else{
            Valid.pindah(evt, BtnBatal, BtnEdit);
        }
}//GEN-LAST:event_BtnHapusKeyPressed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        if(TKd.getText().trim().equals("")){
            Valid.textKosong(TKd,"No Bed");
        }else if(TBangsal.getText().trim().equals("")){
            Valid.textKosong(TBangsal,"Bangsal");
        }else if(TTarif.getText().trim().equals("")){
            Valid.textKosong(TTarif,"Tarif");
        }else if(Kelas.getText().trim().equals("")){
            Valid.textKosong(Kelas,"Kelas");
        }else{
            Sequel.mengedit("kamar","kd_kamar='"+tbKamar.getValueAt(tbKamar.getSelectedRow(),0).toString() +"'","kd_bangsal='"+kd_bangsal.getText()+
                    "',trf_kamar='"+TTarif.getText()+
                    "',status='"+CmbStatus.getSelectedItem()+"',kelas='"+Kelas.getText()+"',kd_kamar='"+TKd.getText()+"'");
            if(tabMode.getRowCount()!=0){tampil();}
            emptTeks();
        }
}//GEN-LAST:event_BtnEditActionPerformed

    private void BtnEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnEditKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnEditActionPerformed(null);
        }else{
            Valid.pindah(evt, BtnHapus, BtnPrint);
        }
}//GEN-LAST:event_BtnEditKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            dispose();
        }else{Valid.pindah(evt,BtnEdit,TCari);}
}//GEN-LAST:event_BtnKeluarKeyPressed

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if(! TCari.getText().trim().equals("")){
            BtnCariActionPerformed(evt);
        }
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, data sudah habis. Tidak ada data yang bisa anda print...!!!!");
            BtnBatal.requestFocus();
        }else if(tabMode.getRowCount()!=0){
            if((TCari.getText().trim().equals(""))&&(panelCari.isVisible()==false)){
                Valid.MyReport("rptKamar.jrxml","report","::[ Data Nomor Kamar ]::","select kd_kamar,kamar.kd_bangsal,bangsal.nm_bangsal, "+
                               "kamar.kelas,trf_kamar,status "+
                               "from bangsal,kamar "+
                               "where kamar.kd_bangsal=bangsal.kd_bangsal "+
                               "order by kd_kamar");
            }else if((! TCari.getText().trim().equals(""))&&(panelCari.isVisible()==false)){
                String sql="kamar.kd_bangsal=bangsal.kd_bangsal ";
                Valid.MyReport("rptKamar.jrxml","report","::[ Data Nomor Kamar ]::","select kd_kamar,kamar.kd_bangsal,bangsal.nm_bangsal, "+
                               "kamar.kelas,trf_kamar,status "+
                               "from bangsal,kamar where  "+
                               sql+"and kd_kamar like '%"+TCari.getText().trim()+"%' or "+
                               sql+"and kamar.kd_bangsal like '%"+TCari.getText().trim()+"%' or "+
                               sql+"and bangsal.nm_bangsal like '%"+TCari.getText().trim()+"%' or "+
                               sql+"and kamar.kelas like '%"+TCari.getText().trim()+"%' or "+
                               sql+"and trf_kamar like '%"+TCari.getText().trim()+"%' or "+
                               sql+"and status like '%"+TCari.getText().trim()+"%' "+
                               "order by kd_kamar ");
            }else if((TCari.getText().trim().equals(""))&&(panelCari.isVisible()==true)&&(CmbCrIsi.getItemCount()>0)){
                String key="";
                if(BangsalCari.getText().equals("")&&CmbCrIsi.getSelectedItem().toString().equals(" ")){
                     key="";
                }else if((! BangsalCari.getText().equals(""))&&CmbCrIsi.getSelectedItem().toString().equals(" ")){
                     key="and bangsal.nm_bangsal like '%"+BangsalCari.getText().trim()+"%' ";
                }else if((! BangsalCari.getText().equals(""))&&(! CmbCrIsi.getSelectedItem().toString().equals(" "))){
                     key="and bangsal.nm_bangsal like '%"+BangsalCari.getText().trim()+"%' "+
                         "and status like '%"+CmbCrIsi.getSelectedItem().toString().trim()+"%' ";
                }else if((BangsalCari.getText().equals(""))&&(! CmbCrIsi.getSelectedItem().toString().equals(" "))){
                     key="and status like '%"+CmbCrIsi.getSelectedItem().toString().trim()+"%' ";
                }     
                Valid.MyReport("rptKamar.jrxml","report","::[ Data Nomor Kamar ]::","select kd_kamar,kamar.kd_bangsal,bangsal.nm_bangsal, "+
                               "kamar.kelas,trf_kamar,status "+
                               "from bangsal,kamar "+
                               "where kamar.kd_bangsal=bangsal.kd_bangsal "+key+
                               " order by kd_kamar");
            }
        }

        this.setCursor(Cursor.getDefaultCursor());
}//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPrintKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnPrintActionPerformed(null);
        }else{
            Valid.pindah(evt, BtnEdit, BtnKeluar);
        }
}//GEN-LAST:event_BtnPrintKeyPressed

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnCariActionPerformed(null);
        }else{Valid.pindah(evt, BtnKeluar, BtnCari);}
}//GEN-LAST:event_TCariKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        tampil();
}//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnCariActionPerformed(null);
        }else{
            Valid.pindah(evt, TCari, BtnAll);
        }
}//GEN-LAST:event_BtnCariKeyPressed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        CmbCrIsi.setSelectedItem(" ");
        BangsalCari.setText("");
        kdbangsalcari.setText("");
        TCari.setText("");
        tampil();
}//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tampil();
            TCari.setText("");
        }else{
            Valid.pindah(evt, BtnCari, kd_bangsal);
        }
}//GEN-LAST:event_BtnAllKeyPressed

    private void CmbCrIsiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CmbCrIsiKeyPressed
        Valid.pindah(evt,kdbangsalcari, TCari);
}//GEN-LAST:event_CmbCrIsiKeyPressed

    private void ChkCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkCariActionPerformed
        if(ChkCari.isSelected()==true){
            panelCari.setVisible(true);
            TCari.setText("");
            tampil();
            posisi();
        }else if(ChkCari.isSelected()==false){
            panelCari.setVisible(false);
            BtnCariActionPerformed(null);
            posisi();
        }
}//GEN-LAST:event_ChkCariActionPerformed

    private void TCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyTyped
        if(ChkCari.isSelected()==true){
            ChkCari.setSelected(false);
            panelCari.setVisible(false);
            posisi();
        }
    }//GEN-LAST:event_TCariKeyTyped

    private void BtnSeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeekActionPerformed
        pilihan=1;
        bangsal.tampil();
        bangsal.emptTeks();        
        bangsal.setSize(internalFrame1.getWidth()-40,internalFrame1.getHeight()-40);
        bangsal.setLocationRelativeTo(internalFrame1);
        bangsal.setVisible(true);
}//GEN-LAST:event_BtnSeekActionPerformed

    private void BtnSeekKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSeekKeyPressed
        Valid.pindah(evt,kd_bangsal,BtnSimpan);
}//GEN-LAST:event_BtnSeekKeyPressed

    private void tbKamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKamarMouseClicked
        if(tabMode.getRowCount()!=0){
            try {
                getData();
            } catch (java.lang.NullPointerException e) {
            }
            
            if((var.getStatus()==true)&&(evt.getClickCount()==2)){
                dispose();
            }
            
        }
}//GEN-LAST:event_tbKamarMouseClicked

    private void tbKamarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbKamarKeyPressed
        if(tabMode.getRowCount()!=0){
            if((evt.getKeyCode()==KeyEvent.VK_ENTER)||(evt.getKeyCode()==KeyEvent.VK_UP)||(evt.getKeyCode()==KeyEvent.VK_DOWN)){
                try {
                    getData();
                } catch (java.lang.NullPointerException e) {
                }
            }
            
            if((var.getStatus()==true)&&(evt.getKeyCode()==KeyEvent.VK_SPACE)){
                dispose();
            }
        }
}//GEN-LAST:event_tbKamarKeyPressed

private void kd_bangsalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kd_bangsalKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Sequel.cariIsi("select bangsal.nm_bangsal from bangsal where bangsal.kd_bangsal=?", TBangsal,kd_bangsal.getText());
        }else{
            Valid.pindah(evt, TKd,TTarif);
        }
}//GEN-LAST:event_kd_bangsalKeyPressed

private void kdbangsalcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kdbangsalcariKeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Sequel.cariIsi("select bangsal.nm_bangsal from bangsal where bangsal.kd_bangsal=?",BangsalCari,kdbangsalcari.getText());
            tampil();
        }else{
            Valid.pindah(evt, TCari,CmbCrIsi);
        }
}//GEN-LAST:event_kdbangsalcariKeyPressed

private void BtnSeek1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeek1ActionPerformed
        pilihan=2;        
        bangsal.tampil();
        bangsal.emptTeks();        
        bangsal.setSize(internalFrame1.getWidth()-40,internalFrame1.getHeight()-40);
        bangsal.setLocationRelativeTo(internalFrame1);
        bangsal.setVisible(true);
}//GEN-LAST:event_BtnSeek1ActionPerformed

private void BtnSeek1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSeek1KeyPressed
   Valid.pindah(evt,kdbangsalcari,CmbCrIsi);
}//GEN-LAST:event_BtnSeek1KeyPressed

private void CmbCrIsiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CmbCrIsiItemStateChanged
    tampil();
}//GEN-LAST:event_CmbCrIsiItemStateChanged

private void KelasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KelasKeyPressed
   Valid.pindah(evt,CmbStatus,BtnSimpan);
}//GEN-LAST:event_KelasKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgKamar dialog = new DlgKamar(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.TextBox BangsalCari;
    private widget.Button BtnAll;
    private widget.Button BtnBatal;
    private widget.Button BtnCari;
    private widget.Button BtnEdit;
    private widget.Button BtnHapus;
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.Button BtnSeek;
    private widget.Button BtnSeek1;
    private widget.Button BtnSimpan;
    private widget.CekBox ChkCari;
    private widget.ComboBox CmbCrIsi;
    private widget.ComboBox CmbStatus;
    private widget.TextBox Kelas;
    private widget.Label LCount;
    private javax.swing.JPanel PanelCariUtama;
    private widget.ScrollPane Scroll;
    private widget.TextBox TBangsal;
    private widget.TextBox TCari;
    private widget.TextBox TKd;
    private widget.TextBox TTarif;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel11;
    private widget.Label jLabel13;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private widget.Label jLabel5;
    private widget.Label jLabel6;
    private widget.Label jLabel7;
    private widget.Label jLabel8;
    private widget.Label jLabel9;
    private widget.TextBox kd_bangsal;
    private widget.TextBox kdbangsalcari;
    private widget.panelisi panelCari;
    private javax.swing.JPanel panelCariKategori;
    private widget.panelisi panelGlass4;
    private widget.panelisi panelGlass5;
    private widget.panelisi panelGlass6;
    private widget.Table tbKamar;
    // End of variables declaration//GEN-END:variables

    public void tampil() {
        Valid.tabelKosong(tabMode);
        try{
            PreparedStatement ps=koneksi.prepareStatement("select kamar.kd_kamar,kamar.kd_bangsal,bangsal.nm_bangsal, "+
                   "kamar.kelas,kamar.trf_kamar,kamar.status from bangsal inner join kamar "+
                   "on kamar.kd_bangsal=bangsal.kd_bangsal where "+
                   "bangsal.nm_bangsal like ? and status like ? and kamar.kd_kamar like ? or "+
                   "bangsal.nm_bangsal like ? and status like ? and kamar.kd_bangsal like ? or "+
                   "bangsal.nm_bangsal like ? and status like ? and bangsal.nm_bangsal like ? or "+
                   "bangsal.nm_bangsal like ? and status like ? and kamar.kelas like ? or "+
                   "bangsal.nm_bangsal like ? and status like ? and kamar.trf_kamar like ? or "+
                   "bangsal.nm_bangsal like ? and status like ? and kamar.status like ? "+
                   "order by bangsal.nm_bangsal");
            ps.setString(1,"%"+BangsalCari.getText().trim()+"%");
            ps.setString(2,"%"+CmbCrIsi.getSelectedItem().toString().trim()+"%");
            ps.setString(3,"%"+TCari.getText().trim()+"%");
            ps.setString(4,"%"+BangsalCari.getText().trim()+"%");
            ps.setString(5,"%"+CmbCrIsi.getSelectedItem().toString().trim()+"%");
            ps.setString(6,"%"+TCari.getText().trim()+"%");
            ps.setString(7,"%"+BangsalCari.getText().trim()+"%");
            ps.setString(8,"%"+CmbCrIsi.getSelectedItem().toString().trim()+"%");
            ps.setString(9,"%"+TCari.getText().trim()+"%");
            ps.setString(10,"%"+BangsalCari.getText().trim()+"%");
            ps.setString(11,"%"+CmbCrIsi.getSelectedItem().toString().trim()+"%");
            ps.setString(12,"%"+TCari.getText().trim()+"%");
            ps.setString(13,"%"+BangsalCari.getText().trim()+"%");
            ps.setString(14,"%"+CmbCrIsi.getSelectedItem().toString().trim()+"%");
            ps.setString(15,"%"+TCari.getText().trim()+"%");
            ps.setString(16,"%"+BangsalCari.getText().trim()+"%");
            ps.setString(17,"%"+CmbCrIsi.getSelectedItem().toString().trim()+"%");
            ps.setString(18,"%"+TCari.getText().trim()+"%");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                String[] data={rs.getString(1),
                               rs.getString(2),
                               rs.getString(3),
                               rs.getString(4),
                               Valid.SetAngka(rs.getDouble(5)),
                               rs.getString(6)};
                tabMode.addRow(data);
            }
            //rs.close();
            //stat.close();
        }catch(SQLException e){
            System.out.println("Error : "+e);
        }
        LCount.setText(""+tabMode.getRowCount());
    }

    private void posisi() {
        if(panelCari.isVisible()==false){
            panelCariKategori.setPreferredSize(new Dimension(WIDTH,22));
            PanelCariUtama.setPreferredSize(new Dimension(WIDTH,122));
        }else if(panelCari.isVisible()==true){
            panelCariKategori.setPreferredSize(new Dimension(WIDTH,61));
            PanelCariUtama.setPreferredSize(new Dimension(WIDTH,161));
        }
    }

    public void emptTeks() {
        TKd.setText("");
        TTarif.setText("");
        kd_bangsal.setText("");
        TBangsal.setText("");
        CmbStatus.setSelectedIndex(0);
        Valid.autoNomer(" kamar ","K",7,TKd);
        TKd.requestFocus();
    }

    private void getData() {
        int row=tbKamar.getSelectedRow();
        if(row!= -1){
            TKd.setText(tbKamar.getValueAt(row,0).toString());
            kd_bangsal.setText(tbKamar.getValueAt(row,1).toString());
            TBangsal.setText(tbKamar.getValueAt(row,2).toString());
            Kelas.setText(tbKamar.getValueAt(row,3).toString());
            TTarif.setText(tbKamar.getValueAt(row,4).toString());
            CmbStatus.setSelectedItem(tbKamar.getValueAt(row,5).toString());
        }

    }

    public void load() {
        kdbangsalcari.setText("");
        BangsalCari.setText("");
        CmbCrIsi.setSelectedItem(" ");
    }    

    public JTextField getTextField(){
        return TKd;
    }

    public JTable getTable(){
        return tbKamar;
    }
       
     public void isCek(){
        BtnSimpan.setEnabled(var.getkamar());
        BtnHapus.setEnabled(var.getkamar());
        BtnEdit.setEnabled(var.getkamar());
        BtnPrint.setEnabled(var.getkamar());
     }
     
    

 
}
