package khanzahms;
import fungsi.koneksiDB;
import fungsi.batasInput;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.WarnaTable;
import fungsi.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public class DlgPresensi extends javax.swing.JDialog {
    private Connection connect=koneksiDB.condb();
    private DefaultTableModel tabMode;
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();

    /** Creates new form DlgProgramStudi */
    public DlgPresensi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocation(8,1);
        setSize(885,674);
        Object[] row={"<html><font color='#b95656' face='Tahoma' size='3'>NIK",
                      "<html><font color='#b95656' face='Tahoma' size='3'>Nama",
                      "<html><font color='#b95656' face='Tahoma' size='3'>Shift",
                      "<html><font color='#b95656' face='Tahoma' size='3'>Jam Datang",
                      "<html><font color='#b95656' face='Tahoma' size='3'>Jam Pulang",
                      "<html><font color='#b95656' face='Tahoma' size='3'>Status",
                      "<html><font color='#b95656' face='Tahoma' size='3'>Keterlambatan",
                      "<html><font color='#b95656' face='Tahoma' size='3'>Durasi"};
        tabMode=new DefaultTableModel(null,row){
              @Override public boolean isCellEditable(int rowIndex, int colIndex){return false;}
        };

        tbPegawai.setModel(tabMode);
        tbPegawai.setPreferredScrollableViewportSize(new Dimension(500,500));
        tbPegawai.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (int i = 0; i < 8; i++) {
            TableColumn column = tbPegawai.getColumnModel().getColumn(i);
            if(i==0){
                column.setPreferredWidth(100);
            }else if(i==1){
                column.setPreferredWidth(350);
            }else if(i==2){
                column.setPreferredWidth(150);
            }else if(i==3){
                column.setPreferredWidth(150);
            }else if(i==4){
                column.setPreferredWidth(150);
            }else if(i==5){
                column.setPreferredWidth(150);
            }else if(i==6){
                column.setPreferredWidth(150);
            }else if(i==7){
                column.setPreferredWidth(150);
            }
        }
        tbPegawai.setDefaultRenderer(Object.class, new WarnaTable());

        Bcd.setDocument(new batasInput((int)25).getKata(Bcd));
        
        TCari.setDocument(new batasInput((int)100).getKata(TCari));

        DlgInput.setSize(744,172);
        DlgInput.setVisible(false);
    }
    private Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DlgInput = new javax.swing.JDialog();
        panelJudul2 = new widget.PanelJudul();
        lblKtg = new widget.Label();
        jLabel3 = new widget.Label();
        panel2 = new widget.Panel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new widget.Label();
        internalFrame2 = new widget.InternalFrame();
        label2 = new widget.Label();
        BtnClose = new widget.Button();
        BtnSimpan = new widget.Button();
        BtnBatal = new widget.Button();
        label23 = new widget.Label();
        Bcd = new widget.PasswordBox();
        Shift = new widget.ComboBox();
        label24 = new widget.Label();
        jamdatang = new widget.TextBox();
        Idpresensi = new widget.TextBox();
        jampulang = new widget.TextBox();
        internalFrame1 = new widget.InternalFrame();
        jPanel2 = new widget.panelisi();
        jPanel4 = new widget.panelisi();
        label9 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        label10 = new widget.Label();
        LCount = new widget.Label();
        jPanel5 = new widget.panelisi();
        BtnTambah = new widget.Button();
        BtnAll = new widget.Button();
        BtnKeluar = new widget.Button();
        scrollPane1 = new widget.ScrollPane();
        tbPegawai = new widget.Table();
        panelJudul1 = new widget.PanelJudul();
        jLabel1 = new widget.Label();

        DlgInput.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DlgInput.setModal(true);
        DlgInput.setName("DlgInput"); // NOI18N
        DlgInput.setResizable(false);
        DlgInput.setUndecorated(true);

        panelJudul2.setName("panelJudul2"); // NOI18N
        panelJudul2.setPreferredSize(new java.awt.Dimension(522, 40));
        panelJudul2.setLayout(new java.awt.BorderLayout());

        lblKtg.setBackground(new java.awt.Color(0, 100, 0));
        lblKtg.setFont(new java.awt.Font("Tahoma", 3, 14));
        lblKtg.setForeground(new java.awt.Color(202, 202, 142));
        lblKtg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKtg.setText(":: PRESENSI MASUK & PULANG ::         ");
        lblKtg.setIconTextGap(2);
        lblKtg.setName("lblKtg"); // NOI18N
        panelJudul2.add(lblKtg, java.awt.BorderLayout.CENTER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/file-edit-32x32.png"))); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(35, 35));
        panelJudul2.add(jLabel3, java.awt.BorderLayout.LINE_START);

        DlgInput.getContentPane().add(panelJudul2, java.awt.BorderLayout.PAGE_START);

        panel2.setName("panel2"); // NOI18N
        panel2.setPreferredSize(new java.awt.Dimension(440, 25));
        panel2.setLayout(new java.awt.BorderLayout());

        jSeparator3.setBackground(new java.awt.Color(0, 50, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 50, 0));
        jSeparator3.setName("jSeparator3"); // NOI18N
        jSeparator3.setPreferredSize(new java.awt.Dimension(1, 1));
        panel2.add(jSeparator3, java.awt.BorderLayout.PAGE_START);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setForeground(new java.awt.Color(202, 202, 142));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(":: Semua field wajib diisi ::");
        jLabel6.setName("jLabel6"); // NOI18N
        panel2.add(jLabel6, java.awt.BorderLayout.CENTER);

        DlgInput.getContentPane().add(panel2, java.awt.BorderLayout.PAGE_END);

        internalFrame2.setName("internalFrame2"); // NOI18N
        internalFrame2.setLayout(null);

        label2.setText("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        label2.setFont(new java.awt.Font("Tahoma", 0, 12));
        label2.setName("label2"); // NOI18N
        internalFrame2.add(label2);
        label2.setBounds(-10, 37, 820, 17);

        BtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnClose.setMnemonic('C');
        BtnClose.setText("Tutup");
        BtnClose.setToolTipText("Alt+C");
        BtnClose.setFont(new java.awt.Font("Tahoma", 1, 12));
        BtnClose.setName("BtnClose"); // NOI18N
        BtnClose.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });
        BtnClose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCloseKeyPressed(evt);
            }
        });
        internalFrame2.add(BtnClose);
        BtnClose.setBounds(630, 60, 100, 30);

        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16i.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setText("Simpan");
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setFont(new java.awt.Font("Tahoma", 1, 12));
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        BtnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSimpanKeyPressed(evt);
            }
        });
        internalFrame2.add(BtnSimpan);
        BtnSimpan.setBounds(13, 60, 100, 30);

        BtnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Cancel-2-16x16.png"))); // NOI18N
        BtnBatal.setMnemonic('B');
        BtnBatal.setText("Baru");
        BtnBatal.setToolTipText("Alt+B");
        BtnBatal.setFont(new java.awt.Font("Tahoma", 1, 12));
        BtnBatal.setName("BtnBatal"); // NOI18N
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        BtnBatal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnBatalKeyPressed(evt);
            }
        });
        internalFrame2.add(BtnBatal);
        BtnBatal.setBounds(125, 60, 100, 30);

        label23.setText("Shift :");
        label23.setFont(new java.awt.Font("Tahoma", 0, 12));
        label23.setName("label23"); // NOI18N
        label23.setPreferredSize(new java.awt.Dimension(65, 23));
        internalFrame2.add(label23);
        label23.setBounds(10, 12, 90, 23);

        Bcd.setForeground(new java.awt.Color(91, 137, 58));
        Bcd.setName("Bcd"); // NOI18N
        Bcd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BcdKeyPressed(evt);
            }
        });
        internalFrame2.add(Bcd);
        Bcd.setBounds(371, 12, 290, 23);

        Shift.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pagi", "Siang", "Malam", "Midle Pagi1", "Midle Pagi2", "Midle Siang1", "Midle Siang2", "Midle Siang3", "Midle Malam1", "Midle Malam2" }));
        Shift.setFont(new java.awt.Font("Tahoma", 0, 12));
        Shift.setName("Shift"); // NOI18N
        Shift.setPreferredSize(new java.awt.Dimension(80, 23));
        internalFrame2.add(Shift);
        Shift.setBounds(104, 12, 110, 23);

        label24.setText("ID User :");
        label24.setFont(new java.awt.Font("Tahoma", 0, 12));
        label24.setName("label24"); // NOI18N
        label24.setPreferredSize(new java.awt.Dimension(65, 23));
        internalFrame2.add(label24);
        label24.setBounds(257, 12, 110, 23);

        jamdatang.setFont(new java.awt.Font("Tahoma", 0, 12));
        jamdatang.setName("jamdatang"); // NOI18N
        jamdatang.setPreferredSize(new java.awt.Dimension(207, 23));
        jamdatang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jamdatangKeyPressed(evt);
            }
        });
        internalFrame2.add(jamdatang);
        jamdatang.setBounds(440, 230, 207, 23);

        Idpresensi.setFont(new java.awt.Font("Tahoma", 0, 12));
        Idpresensi.setName("Idpresensi"); // NOI18N
        Idpresensi.setPreferredSize(new java.awt.Dimension(207, 23));
        Idpresensi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IdpresensiKeyPressed(evt);
            }
        });
        internalFrame2.add(Idpresensi);
        Idpresensi.setBounds(220, 200, 207, 23);

        jampulang.setFont(new java.awt.Font("Tahoma", 0, 12));
        jampulang.setName("jampulang"); // NOI18N
        jampulang.setPreferredSize(new java.awt.Dimension(207, 23));
        jampulang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jampulangKeyPressed(evt);
            }
        });
        internalFrame2.add(jampulang);
        jampulang.setBounds(220, 230, 207, 23);

        DlgInput.getContentPane().add(internalFrame2, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);

        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(816, 100));
        jPanel2.setLayout(new java.awt.BorderLayout(1, 1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 212, 152)));
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 44));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 9));

        label9.setText("Key Word :");
        label9.setFont(new java.awt.Font("Tahoma", 0, 12));
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(70, 23));
        jPanel4.add(label9);

        TCari.setFont(new java.awt.Font("Tahoma", 0, 12));
        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(350, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        jPanel4.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('1');
        BtnCari.setToolTipText("Alt+1");
        BtnCari.setFont(new java.awt.Font("Tahoma", 1, 12));
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        jPanel4.add(BtnCari);

        label10.setText("Record :");
        label10.setFont(new java.awt.Font("Tahoma", 0, 12));
        label10.setName("label10"); // NOI18N
        label10.setPreferredSize(new java.awt.Dimension(70, 23));
        jPanel4.add(label10);

        LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount.setText("0");
        LCount.setFont(new java.awt.Font("Tahoma", 0, 12));
        LCount.setName("LCount"); // NOI18N
        LCount.setPreferredSize(new java.awt.Dimension(60, 23));
        jPanel4.add(LCount);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 212, 152)));
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 44));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/add-file-16x16.png"))); // NOI18N
        BtnTambah.setMnemonic('P');
        BtnTambah.setText("Presensi");
        BtnTambah.setToolTipText("Alt+P");
        BtnTambah.setFont(new java.awt.Font("Tahoma", 1, 12));
        BtnTambah.setName("BtnTambah"); // NOI18N
        BtnTambah.setPreferredSize(new java.awt.Dimension(120, 30));
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });
        BtnTambah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnTambahKeyPressed(evt);
            }
        });
        jPanel5.add(BtnTambah);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('2');
        BtnAll.setText("Semua");
        BtnAll.setToolTipText("Alt+2");
        BtnAll.setFont(new java.awt.Font("Tahoma", 1, 12));
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        jPanel5.add(BtnAll);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setFont(new java.awt.Font("Tahoma", 1, 12));
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        jPanel5.add(BtnKeluar);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        internalFrame1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        scrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 212, 152)));
        scrollPane1.setName("scrollPane1"); // NOI18N
        scrollPane1.setOpaque(true);

        tbPegawai.setAutoCreateRowSorter(true);
        tbPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPegawai.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbPegawai.setFont(new java.awt.Font("Tahoma", 0, 12));
        tbPegawai.setName("tbPegawai"); // NOI18N
        scrollPane1.setViewportView(tbPegawai);

        internalFrame1.add(scrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        panelJudul1.setName("panelJudul1"); // NOI18N
        panelJudul1.setPreferredSize(new java.awt.Dimension(163, 28));
        panelJudul1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 100, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 13));
        jLabel1.setForeground(new java.awt.Color(202, 202, 142));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(":: DATA PRESENSI ::");
        jLabel1.setIconTextGap(2);
        jLabel1.setName("jLabel1"); // NOI18N
        panelJudul1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelJudul1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnCariActionPerformed(null);
        }else{Valid.pindah(evt, BtnKeluar, BtnCari);}
}//GEN-LAST:event_TCariKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        prosesCari("select  pegawai.id, "+
                "pegawai.nik, "+
                "pegawai.nama, "+
                "temporary_presensi.shift,"+
                "temporary_presensi.jam_datang, "+
                "temporary_presensi.jam_pulang, "+
                "temporary_presensi.status, "+
                "temporary_presensi.keterlambatan, "+
                "temporary_presensi.durasi "+
                " from pegawai inner join temporary_presensi on pegawai.id=temporary_presensi.id where "+
                   " pegawai.nik like '%"+TCari.getText().trim()+"%' "+
                   "or pegawai.nama like '%"+TCari.getText().trim()+"%' "+
                   "or temporary_presensi.shift like '%"+TCari.getText().trim()+"%' "+
                   "or temporary_presensi.status like '%"+TCari.getText().trim()+"%' "+
                   "or temporary_presensi.keterlambatan like '%"+TCari.getText().trim()+"%' "+
                   "or temporary_presensi.jam_datang like '%"+TCari.getText().trim()+"%' "+
                   "or temporary_presensi.jam_pulang like '%"+TCari.getText().trim()+"%' order by temporary_presensi.jam_datang ");
}//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnCariActionPerformed(null);
        }else{
            Valid.pindah(evt, TCari, BtnAll);
        }
}//GEN-LAST:event_BtnCariKeyPressed

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
        emptTeks();
        DlgInput.dispose();
}//GEN-LAST:event_BtnCloseActionPerformed

    private void BtnCloseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCloseKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            DlgInput.dispose();
        }else{Valid.pindah(evt,BtnBatal,BtnClose);}
}//GEN-LAST:event_BtnCloseKeyPressed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        if(Bcd.getText().trim().equals("")){
            Valid.textKosong(Bcd,"ID");
        }else{
            try {
                Statement stat=connect.createStatement();
                ResultSet rs=stat.executeQuery("select * from barcode where barcode='"+Bcd.getText()+"'");
                rs.last();
                if(rs.getRow()>=1){
                        //----------------cari id Barcode-------------------------------------------
                        Sequel.cariIsi("select id from barcode where barcode='"+Bcd.getText()+"'", Idpresensi);
                        Sequel.cariIsi("select jam_jaga.jam_masuk from jam_jaga inner join pegawai on pegawai.departemen=jam_jaga.dep_id "+
                                " where jam_jaga.shift='"+Shift.getSelectedItem().toString()+"' and pegawai.id='"+Idpresensi.getText()+"'", jamdatang);
                        try {
                            //simpan ke temporary presensi
                            String jam="now()";
                            if(!jamdatang.getText().equals("")){
                                jam="CONCAT(CURRENT_DATE(),' "+jamdatang.getText()+"')";
                            }
                            stat.execute("insert into temporary_presensi values "+
                               "('"+Idpresensi.getText()+"','"+Shift.getSelectedItem()+"',NOW(),NULL,"+
                               "if(TIME_TO_SEC(now())-TIME_TO_SEC("+jam+")>600,'Terlambat','Tepat Waktu'),"+
                               "if(TIME_TO_SEC(now())-TIME_TO_SEC("+jam+")>600,SEC_TO_TIME(TIME_TO_SEC(now())-TIME_TO_SEC("+jam+")),''),'','')");
                        }catch (Exception ex) {
                            //System.out.println(ex);                            
                            try{
                                //update jam pulang dan durasi sebelum disimpan ke table rekap presensi
                                stat.execute("update temporary_presensi set jam_pulang=NOW(),"+
                                    "durasi=(SEC_TO_TIME(unix_timestamp(now()) - unix_timestamp(jam_datang)))"+
                                    " where id='"+Idpresensi.getText()+"'");
                                //cari dulu data di temporary yang mau disimpan ke rekap presensi
                                ResultSet rs2=stat.executeQuery("select * from temporary_presensi where id='"+Idpresensi.getText()+"'");
                                if(rs2.next()){
                                    try{
                                        //simpan ke dalam rekap presensi
                                        stat.execute("insert into rekap_presensi values "+
                                                "('"+rs2.getString(1) +"','"+rs2.getString(2) +"','"+rs2.getString(3) +
                                                "','"+rs2.getString(4) +"','"+rs2.getString(5) +"','"+rs2.getString(6) +
                                                "','"+rs2.getString(7) +"','','')");
                                        stat.execute("delete from temporary_presensi where id='"+Idpresensi.getText()+"'");
                                        //jamdatang.setText("");
                                        //jampulang.setText("");
                                    }catch (Exception er) {         
                                        System.out.println(er);  
                                        JOptionPane.showMessageDialog(null,"Maaf, Anda sudah presensi Pulang ...!");
                                    }  
                                }
                            }catch (Exception er) {                                
                                System.out.println(er);  
                            }                               
                        }
                    tampil("");
                    emptTeks();
                }else if(rs.getRow()==0){
                    JOptionPane.showMessageDialog(null,"Maaf, Gagal Presensi. ID User atau password ada yang salah ...!");
                }
            } catch (SQLException ex) {
                System.out.println(ex);   
            }  
        }
}//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSimpanKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnSimpanActionPerformed(null);
        }else{
            Valid.pindah(evt,Bcd,BtnBatal);
        }
}//GEN-LAST:event_BtnSimpanKeyPressed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed

            emptTeks();
}//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnBatalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnBatalKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            emptTeks();
        }else{Valid.pindah(evt, BtnSimpan, BtnClose);}
}//GEN-LAST:event_BtnBatalKeyPressed

private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
            Bcd.requestFocus();
            lblKtg.setText(":: PRESENSI MASUK & PULANG ::         ");
            //LabelKon.setVisible(true);
            DlgInput.setLocationRelativeTo(null);
            DlgInput.setVisible(true);
        
}//GEN-LAST:event_BtnTambahActionPerformed

private void BtnTambahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnTambahKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnTambahActionPerformed(null);
        }else{
            Valid.pindah(evt, TCari, BtnAll);
        }
}//GEN-LAST:event_BtnTambahKeyPressed

private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        TCari.setText("");
        tampil("");
}//GEN-LAST:event_BtnAllActionPerformed

private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnAllActionPerformed(null);
        }else{
            Valid.pindah(evt, BtnTambah, BtnKeluar);
        }
}//GEN-LAST:event_BtnAllKeyPressed

private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
            dispose();  
}//GEN-LAST:event_BtnKeluarActionPerformed

private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            dispose();  
        }else{Valid.pindah(evt,BtnAll,TCari);}
}//GEN-LAST:event_BtnKeluarKeyPressed

private void IdpresensiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdpresensiKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_IdpresensiKeyPressed

private void BcdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BcdKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnSimpanActionPerformed(null);
        }else{
            Valid.pindah(evt,BtnClose,BtnSimpan);
        }
}//GEN-LAST:event_BcdKeyPressed

private void jamdatangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jamdatangKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_jamdatangKeyPressed

private void jampulangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jampulangKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_jampulangKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgPresensi dialog = new DlgPresensi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.PasswordBox Bcd;
    private widget.Button BtnAll;
    private widget.Button BtnBatal;
    private widget.Button BtnCari;
    private widget.Button BtnClose;
    private widget.Button BtnKeluar;
    private widget.Button BtnSimpan;
    private widget.Button BtnTambah;
    private javax.swing.JDialog DlgInput;
    private widget.TextBox Idpresensi;
    private widget.Label LCount;
    private widget.ComboBox Shift;
    private widget.TextBox TCari;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame2;
    private widget.Label jLabel1;
    private widget.Label jLabel3;
    private widget.Label jLabel6;
    private widget.panelisi jPanel2;
    private widget.panelisi jPanel4;
    private widget.panelisi jPanel5;
    private javax.swing.JSeparator jSeparator3;
    private widget.TextBox jamdatang;
    private widget.TextBox jampulang;
    private widget.Label label10;
    private widget.Label label2;
    private widget.Label label23;
    private widget.Label label24;
    private widget.Label label9;
    private widget.Label lblKtg;
    private widget.Panel panel2;
    private widget.PanelJudul panelJudul1;
    private widget.PanelJudul panelJudul2;
    private widget.ScrollPane scrollPane1;
    private widget.Table tbPegawai;
    // End of variables declaration//GEN-END:variables

    public void tampil(String key) {
        String sql="select  pegawai.id, "+
                "pegawai.nik, "+
                "pegawai.nama, "+
                "temporary_presensi.shift,"+
                "temporary_presensi.jam_datang, "+
                "temporary_presensi.jam_pulang, "+
                "temporary_presensi.status, "+
                "temporary_presensi.keterlambatan, "+
                "temporary_presensi.durasi "+
                " from pegawai inner join temporary_presensi on pegawai.id=temporary_presensi.id order by temporary_presensi.jam_datang";
        prosesCari(sql);
    }

    private void prosesCari(String sql) {
        Valid.tabelKosong(tabMode);
        try{
            java.sql.Statement stat=connect.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            while(rs.next()){
                String[] data={rs.getString(2),
                               rs.getString(3),
                               rs.getString(4),
                               rs.getString(5),
                               rs.getString(6),
                               rs.getString(7),
                               rs.getString(8),
                               rs.getString(9)};
                tabMode.addRow(data);
             }
            rs.close();
            stat.close();
        }catch(SQLException e){
            System.out.println("Error : "+e);
        }
        LCount.setText(""+tabMode.getRowCount());

    }

    public void emptTeks() {
        Bcd.setText("");
    }

 
}
