/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgVakum.java
 *
 * Created on Jun 30, 2010, 7:56:21 PM
 */

package khanzahms;

import fungsi.koneksiDB;
import fungsi.sekuel;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author user_one
 */
public class DlgVakum extends javax.swing.JDialog {
    private final sekuel Sequel=new sekuel();
    private final Connection koneksi=koneksiDB.condb();

    /** Creates new form DlgVakum
     * @param parent
     * @param modal */
    public DlgVakum(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(790,480);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        panelBiasa1 = new widget.PanelBiasa();
        BtnJabatan = new usu.widget.ButtonGlass();
        BtnSpesialis = new usu.widget.ButtonGlass();
        BtnJI = new usu.widget.ButtonGlass();
        BtnKP = new usu.widget.ButtonGlass();
        BtnJP = new usu.widget.ButtonGlass();
        BtnKlinik = new usu.widget.ButtonGlass();
        BtnBangsal = new usu.widget.ButtonGlass();
        BtnKamar = new usu.widget.ButtonGlass();
        BtnKPny = new usu.widget.ButtonGlass();
        BtnPny = new usu.widget.ButtonGlass();
        BtnObat = new usu.widget.ButtonGlass();
        BtnObatPny = new usu.widget.ButtonGlass();
        BtnPtg = new usu.widget.ButtonGlass();
        BtnDokter = new usu.widget.ButtonGlass();
        BtnJadPrak = new usu.widget.ButtonGlass();
        BtnPasien = new usu.widget.ButtonGlass();
        BtnIbu = new usu.widget.ButtonGlass();
        BtnBayi = new usu.widget.ButtonGlass();
        BtnReg = new usu.widget.ButtonGlass();
        BtnRegIbu = new usu.widget.ButtonGlass();
        BtnRegBayi = new usu.widget.ButtonGlass();
        BtnKmrInap = new usu.widget.ButtonGlass();
        BtnKmrInapIbu = new usu.widget.ButtonGlass();
        BtnKmrInapBayi = new usu.widget.ButtonGlass();
        BtnBill = new usu.widget.ButtonGlass();
        BtnBillIbu = new usu.widget.ButtonGlass();
        BtnBillBayi = new usu.widget.ButtonGlass();
        BtnRwtJln = new usu.widget.ButtonGlass();
        BtnResep = new usu.widget.ButtonGlass();
        BtnRujuk = new usu.widget.ButtonGlass();
        BtnRawatInap = new usu.widget.ButtonGlass();
        BtnBeriInfus = new usu.widget.ButtonGlass();
        BtnBrObat = new usu.widget.ButtonGlass();
        BtnRwtJlnIbu = new usu.widget.ButtonGlass();
        BtnResepIbu = new usu.widget.ButtonGlass();
        BtnRujukIbu = new usu.widget.ButtonGlass();
        BtnRawatInapIbu = new usu.widget.ButtonGlass();
        BtnBeriInfusIbu = new usu.widget.ButtonGlass();
        BtnBrObatIbu = new usu.widget.ButtonGlass();
        BtnRwtJlnBayi = new usu.widget.ButtonGlass();
        BtnResepBayi = new usu.widget.ButtonGlass();
        BtnRujukBayi = new usu.widget.ButtonGlass();
        BtnRawatInapBayi = new usu.widget.ButtonGlass();
        BtnBeriInfusBayi = new usu.widget.ButtonGlass();
        BtnBrObatBayi = new usu.widget.ButtonGlass();
        BtnPasienMati = new usu.widget.ButtonGlass();
        BtnIbuMati = new usu.widget.ButtonGlass();
        BtnBayiMati = new usu.widget.ButtonGlass();
        BtnPesan = new usu.widget.ButtonGlass();
        panelGlass1 = new widget.panelisi();
        button1 = new widget.Button();
        jLabel12 = new widget.Label();
        jLabel11 = new widget.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), ".: Silahkan klik tombol untuk menghapus isi table", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 70, 40))); // NOI18N
        internalFrame1.setToolTipText("");
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelBiasa1.setName("panelBiasa1"); // NOI18N
        panelBiasa1.setWarnaAtas(new java.awt.Color(235, 255, 235));
        panelBiasa1.setWarnaBawah(new java.awt.Color(235, 255, 235));
        panelBiasa1.setLayout(new java.awt.GridLayout(12, 6, 5, 5));

        BtnJabatan.setBackground(new java.awt.Color(195, 205, 185));
        BtnJabatan.setForeground(new java.awt.Color(153, 0, 51));
        BtnJabatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/UserSetup.png"))); // NOI18N
        BtnJabatan.setMnemonic('4');
        BtnJabatan.setText("Jabatan");
        BtnJabatan.setToolTipText("Alt+4");
        BtnJabatan.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnJabatan.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnJabatan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnJabatan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnJabatan.setName("BtnJabatan"); // NOI18N
        BtnJabatan.setRoundRect(true);
        BtnJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJabatanActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnJabatan);

        BtnSpesialis.setBackground(new java.awt.Color(195, 205, 185));
        BtnSpesialis.setForeground(new java.awt.Color(153, 0, 51));
        BtnSpesialis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Surgeon.png"))); // NOI18N
        BtnSpesialis.setMnemonic('5');
        BtnSpesialis.setText("Spesialis");
        BtnSpesialis.setToolTipText("Alt+5");
        BtnSpesialis.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnSpesialis.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnSpesialis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnSpesialis.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnSpesialis.setName("BtnSpesialis"); // NOI18N
        BtnSpesialis.setRoundRect(true);
        BtnSpesialis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSpesialisActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnSpesialis);

        BtnJI.setBackground(new java.awt.Color(195, 205, 185));
        BtnJI.setForeground(new java.awt.Color(153, 0, 51));
        BtnJI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/TestTubes.png"))); // NOI18N
        BtnJI.setMnemonic('6');
        BtnJI.setText("Jenis Infus");
        BtnJI.setToolTipText("Alt+6");
        BtnJI.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnJI.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnJI.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnJI.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnJI.setName("BtnJI"); // NOI18N
        BtnJI.setRoundRect(true);
        BtnJI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJIActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnJI);

        BtnKP.setBackground(new java.awt.Color(195, 205, 185));
        BtnKP.setForeground(new java.awt.Color(153, 0, 51));
        BtnKP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept_page.png"))); // NOI18N
        BtnKP.setMnemonic('7');
        BtnKP.setText("Ktg. Perawatan");
        BtnKP.setToolTipText("Alt+7");
        BtnKP.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnKP.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnKP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnKP.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnKP.setName("BtnKP"); // NOI18N
        BtnKP.setRoundRect(true);
        BtnKP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKPActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnKP);

        BtnJP.setBackground(new java.awt.Color(195, 205, 185));
        BtnJP.setForeground(new java.awt.Color(153, 0, 51));
        BtnJP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/KidneyDish.png"))); // NOI18N
        BtnJP.setMnemonic('8');
        BtnJP.setText("Jenis Perawatan");
        BtnJP.setToolTipText("Alt+8");
        BtnJP.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnJP.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnJP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnJP.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnJP.setName("BtnJP"); // NOI18N
        BtnJP.setRoundRect(true);
        BtnJP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJPActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnJP);

        BtnKlinik.setBackground(new java.awt.Color(195, 205, 185));
        BtnKlinik.setForeground(new java.awt.Color(153, 0, 51));
        BtnKlinik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/City.png"))); // NOI18N
        BtnKlinik.setMnemonic('9');
        BtnKlinik.setText("Poliklinik");
        BtnKlinik.setToolTipText("Alt+9");
        BtnKlinik.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnKlinik.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnKlinik.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnKlinik.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnKlinik.setName("BtnKlinik"); // NOI18N
        BtnKlinik.setRoundRect(true);
        BtnKlinik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKlinikActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnKlinik);

        BtnBangsal.setBackground(new java.awt.Color(195, 205, 185));
        BtnBangsal.setForeground(new java.awt.Color(153, 0, 51));
        BtnBangsal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Church.png"))); // NOI18N
        BtnBangsal.setMnemonic('0');
        BtnBangsal.setText("Bangsal/Kamar");
        BtnBangsal.setToolTipText("Alt+0");
        BtnBangsal.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnBangsal.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnBangsal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBangsal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnBangsal.setName("BtnBangsal"); // NOI18N
        BtnBangsal.setRoundRect(true);
        BtnBangsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBangsalActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnBangsal);

        BtnKamar.setBackground(new java.awt.Color(195, 205, 185));
        BtnKamar.setForeground(new java.awt.Color(153, 0, 51));
        BtnKamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Hospital.png"))); // NOI18N
        BtnKamar.setMnemonic('A');
        BtnKamar.setText("Nomer Kamar");
        BtnKamar.setToolTipText("Alt+A");
        BtnKamar.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnKamar.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnKamar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnKamar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnKamar.setName("BtnKamar"); // NOI18N
        BtnKamar.setRoundRect(true);
        BtnKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKamarActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnKamar);

        BtnKPny.setBackground(new java.awt.Color(195, 205, 185));
        BtnKPny.setForeground(new java.awt.Color(153, 0, 51));
        BtnKPny.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Edit.png"))); // NOI18N
        BtnKPny.setMnemonic('B');
        BtnKPny.setText("Kategori Penyakit");
        BtnKPny.setToolTipText("Alt+B");
        BtnKPny.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnKPny.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnKPny.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnKPny.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnKPny.setName("BtnKPny"); // NOI18N
        BtnKPny.setRoundRect(true);
        BtnKPny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKPnyActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnKPny);

        BtnPny.setBackground(new java.awt.Color(195, 205, 185));
        BtnPny.setForeground(new java.awt.Color(153, 0, 51));
        BtnPny.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/BandAid.png"))); // NOI18N
        BtnPny.setMnemonic('C');
        BtnPny.setText("Penyakit");
        BtnPny.setToolTipText("Alt+C");
        BtnPny.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnPny.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnPny.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnPny.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnPny.setName("BtnPny"); // NOI18N
        BtnPny.setRoundRect(true);
        BtnPny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPnyActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnPny);

        BtnObat.setBackground(new java.awt.Color(195, 205, 185));
        BtnObat.setForeground(new java.awt.Color(153, 0, 51));
        BtnObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Pills.png"))); // NOI18N
        BtnObat.setMnemonic('D');
        BtnObat.setText("Obat");
        BtnObat.setToolTipText("Alt+D");
        BtnObat.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnObat.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnObat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnObat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnObat.setName("BtnObat"); // NOI18N
        BtnObat.setRoundRect(true);
        BtnObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnObatActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnObat);

        BtnObatPny.setBackground(new java.awt.Color(195, 205, 185));
        BtnObatPny.setForeground(new java.awt.Color(153, 0, 51));
        BtnObatPny.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Vial-Pills.png"))); // NOI18N
        BtnObatPny.setMnemonic('E');
        BtnObatPny.setText("Obat Penyakit");
        BtnObatPny.setToolTipText("Alt+E");
        BtnObatPny.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnObatPny.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnObatPny.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnObatPny.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnObatPny.setName("BtnObatPny"); // NOI18N
        BtnObatPny.setRoundRect(true);
        BtnObatPny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnObatPnyActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnObatPny);

        BtnPtg.setBackground(new java.awt.Color(195, 205, 185));
        BtnPtg.setForeground(new java.awt.Color(153, 0, 51));
        BtnPtg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Add patient.png"))); // NOI18N
        BtnPtg.setMnemonic('F');
        BtnPtg.setText("Petugas");
        BtnPtg.setToolTipText("Alt+F");
        BtnPtg.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnPtg.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnPtg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnPtg.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnPtg.setName("BtnPtg"); // NOI18N
        BtnPtg.setRoundRect(true);
        BtnPtg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPtgActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnPtg);

        BtnDokter.setBackground(new java.awt.Color(195, 205, 185));
        BtnDokter.setForeground(new java.awt.Color(153, 0, 51));
        BtnDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Doctor.png"))); // NOI18N
        BtnDokter.setMnemonic('G');
        BtnDokter.setText("Dokter");
        BtnDokter.setToolTipText("Alt+G");
        BtnDokter.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnDokter.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnDokter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnDokter.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnDokter.setName("BtnDokter"); // NOI18N
        BtnDokter.setRoundRect(true);
        BtnDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDokterActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnDokter);

        BtnJadPrak.setBackground(new java.awt.Color(195, 205, 185));
        BtnJadPrak.setForeground(new java.awt.Color(153, 0, 51));
        BtnJadPrak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/History.png"))); // NOI18N
        BtnJadPrak.setMnemonic('I');
        BtnJadPrak.setText("Jadwal Dokter");
        BtnJadPrak.setToolTipText("Alt+I");
        BtnJadPrak.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnJadPrak.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnJadPrak.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnJadPrak.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnJadPrak.setName("BtnJadPrak"); // NOI18N
        BtnJadPrak.setRoundRect(true);
        BtnJadPrak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJadPrakActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnJadPrak);

        BtnPasien.setBackground(new java.awt.Color(195, 205, 185));
        BtnPasien.setForeground(new java.awt.Color(153, 0, 51));
        BtnPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/family24.png"))); // NOI18N
        BtnPasien.setMnemonic('H');
        BtnPasien.setText("Pasien Umum");
        BtnPasien.setToolTipText("Alt+H");
        BtnPasien.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnPasien.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnPasien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnPasien.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnPasien.setName("BtnPasien"); // NOI18N
        BtnPasien.setRoundRect(true);
        BtnPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPasienActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnPasien);

        BtnIbu.setBackground(new java.awt.Color(195, 205, 185));
        BtnIbu.setForeground(new java.awt.Color(153, 0, 51));
        BtnIbu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/family24.png"))); // NOI18N
        BtnIbu.setMnemonic('H');
        BtnIbu.setText("Pasien Asuransi");
        BtnIbu.setToolTipText("Alt+H");
        BtnIbu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnIbu.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnIbu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnIbu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnIbu.setName("BtnIbu"); // NOI18N
        BtnIbu.setRoundRect(true);
        BtnIbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIbuActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnIbu);

        BtnBayi.setBackground(new java.awt.Color(195, 205, 185));
        BtnBayi.setForeground(new java.awt.Color(153, 0, 51));
        BtnBayi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/family24.png"))); // NOI18N
        BtnBayi.setMnemonic('H');
        BtnBayi.setText("Pasien Askes");
        BtnBayi.setToolTipText("Alt+H");
        BtnBayi.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnBayi.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnBayi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBayi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnBayi.setName("BtnBayi"); // NOI18N
        BtnBayi.setRoundRect(true);
        BtnBayi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBayiActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnBayi);

        BtnReg.setBackground(new java.awt.Color(195, 205, 185));
        BtnReg.setForeground(new java.awt.Color(153, 0, 51));
        BtnReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/PatientFile.png"))); // NOI18N
        BtnReg.setMnemonic('J');
        BtnReg.setText("Reg.Prksa Umum");
        BtnReg.setToolTipText("Alt+J");
        BtnReg.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnReg.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnReg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnReg.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnReg.setName("BtnReg"); // NOI18N
        BtnReg.setRoundRect(true);
        BtnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnReg);

        BtnRegIbu.setBackground(new java.awt.Color(195, 205, 185));
        BtnRegIbu.setForeground(new java.awt.Color(153, 0, 51));
        BtnRegIbu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/PatientFile.png"))); // NOI18N
        BtnRegIbu.setMnemonic('J');
        BtnRegIbu.setText("Reg.Prksa Asuransi");
        BtnRegIbu.setToolTipText("Alt+J");
        BtnRegIbu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnRegIbu.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnRegIbu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnRegIbu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnRegIbu.setName("BtnRegIbu"); // NOI18N
        BtnRegIbu.setRoundRect(true);
        BtnRegIbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegIbuActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnRegIbu);

        BtnRegBayi.setBackground(new java.awt.Color(195, 205, 185));
        BtnRegBayi.setForeground(new java.awt.Color(153, 0, 51));
        BtnRegBayi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/PatientFile.png"))); // NOI18N
        BtnRegBayi.setMnemonic('J');
        BtnRegBayi.setText("Reg.Prksa Askes");
        BtnRegBayi.setToolTipText("Alt+J");
        BtnRegBayi.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnRegBayi.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnRegBayi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnRegBayi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnRegBayi.setName("BtnRegBayi"); // NOI18N
        BtnRegBayi.setRoundRect(true);
        BtnRegBayi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegBayiActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnRegBayi);

        BtnKmrInap.setBackground(new java.awt.Color(195, 205, 185));
        BtnKmrInap.setForeground(new java.awt.Color(153, 0, 51));
        BtnKmrInap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/home24.png"))); // NOI18N
        BtnKmrInap.setMnemonic('N');
        BtnKmrInap.setText("Kamar Inap Umum");
        BtnKmrInap.setToolTipText("Alt+N");
        BtnKmrInap.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnKmrInap.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnKmrInap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnKmrInap.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnKmrInap.setName("BtnKmrInap"); // NOI18N
        BtnKmrInap.setRoundRect(true);
        BtnKmrInap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKmrInapActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnKmrInap);

        BtnKmrInapIbu.setBackground(new java.awt.Color(195, 205, 185));
        BtnKmrInapIbu.setForeground(new java.awt.Color(153, 0, 51));
        BtnKmrInapIbu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/home24.png"))); // NOI18N
        BtnKmrInapIbu.setMnemonic('N');
        BtnKmrInapIbu.setText("Kamar Inap Asuransi");
        BtnKmrInapIbu.setToolTipText("Alt+N");
        BtnKmrInapIbu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnKmrInapIbu.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnKmrInapIbu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnKmrInapIbu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnKmrInapIbu.setName("BtnKmrInapIbu"); // NOI18N
        BtnKmrInapIbu.setRoundRect(true);
        BtnKmrInapIbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKmrInapIbuActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnKmrInapIbu);

        BtnKmrInapBayi.setBackground(new java.awt.Color(195, 205, 185));
        BtnKmrInapBayi.setForeground(new java.awt.Color(153, 0, 51));
        BtnKmrInapBayi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/home24.png"))); // NOI18N
        BtnKmrInapBayi.setMnemonic('N');
        BtnKmrInapBayi.setText("Kamar Inap Askes");
        BtnKmrInapBayi.setToolTipText("Alt+N");
        BtnKmrInapBayi.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnKmrInapBayi.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnKmrInapBayi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnKmrInapBayi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnKmrInapBayi.setName("BtnKmrInapBayi"); // NOI18N
        BtnKmrInapBayi.setRoundRect(true);
        BtnKmrInapBayi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKmrInapBayiActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnKmrInapBayi);

        BtnBill.setBackground(new java.awt.Color(195, 205, 185));
        BtnBill.setForeground(new java.awt.Color(153, 0, 51));
        BtnBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Money-32x32.png"))); // NOI18N
        BtnBill.setMnemonic('R');
        BtnBill.setText("Blng.Prw.Umum");
        BtnBill.setToolTipText("Alt+R");
        BtnBill.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnBill.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnBill.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBill.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnBill.setName("BtnBill"); // NOI18N
        BtnBill.setRoundRect(true);
        BtnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBillActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnBill);

        BtnBillIbu.setBackground(new java.awt.Color(195, 205, 185));
        BtnBillIbu.setForeground(new java.awt.Color(153, 0, 51));
        BtnBillIbu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Money-32x32.png"))); // NOI18N
        BtnBillIbu.setMnemonic('R');
        BtnBillIbu.setText("Blng.Prw.Asuransi");
        BtnBillIbu.setToolTipText("Alt+R");
        BtnBillIbu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnBillIbu.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnBillIbu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBillIbu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnBillIbu.setName("BtnBillIbu"); // NOI18N
        BtnBillIbu.setRoundRect(true);
        BtnBillIbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBillIbuActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnBillIbu);

        BtnBillBayi.setBackground(new java.awt.Color(195, 205, 185));
        BtnBillBayi.setForeground(new java.awt.Color(153, 0, 51));
        BtnBillBayi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Money-32x32.png"))); // NOI18N
        BtnBillBayi.setMnemonic('R');
        BtnBillBayi.setText("Blng.Prw.Askes");
        BtnBillBayi.setToolTipText("Alt+R");
        BtnBillBayi.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnBillBayi.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnBillBayi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBillBayi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnBillBayi.setName("BtnBillBayi"); // NOI18N
        BtnBillBayi.setRoundRect(true);
        BtnBillBayi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBillBayiActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnBillBayi);

        BtnRwtJln.setBackground(new java.awt.Color(195, 205, 185));
        BtnRwtJln.setForeground(new java.awt.Color(153, 0, 51));
        BtnRwtJln.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/addressbook-edit24.png"))); // NOI18N
        BtnRwtJln.setMnemonic('K');
        BtnRwtJln.setText("Rw.Jalan Umum");
        BtnRwtJln.setToolTipText("Alt+K");
        BtnRwtJln.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnRwtJln.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnRwtJln.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnRwtJln.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnRwtJln.setName("BtnRwtJln"); // NOI18N
        BtnRwtJln.setRoundRect(true);
        BtnRwtJln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRwtJlnActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnRwtJln);

        BtnResep.setBackground(new java.awt.Color(195, 205, 185));
        BtnResep.setForeground(new java.awt.Color(153, 0, 51));
        BtnResep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Drug-basket-32.png"))); // NOI18N
        BtnResep.setMnemonic('L');
        BtnResep.setText("Resep Obat Umum");
        BtnResep.setToolTipText("Alt+L");
        BtnResep.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnResep.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnResep.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnResep.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnResep.setName("BtnResep"); // NOI18N
        BtnResep.setRoundRect(true);
        BtnResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResepActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnResep);

        BtnRujuk.setBackground(new java.awt.Color(195, 205, 185));
        BtnRujuk.setForeground(new java.awt.Color(153, 0, 51));
        BtnRujuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/PSD24.png"))); // NOI18N
        BtnRujuk.setMnemonic('M');
        BtnRujuk.setText("Rujuk Umum");
        BtnRujuk.setToolTipText("Alt+M");
        BtnRujuk.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnRujuk.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnRujuk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnRujuk.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnRujuk.setName("BtnRujuk"); // NOI18N
        BtnRujuk.setRoundRect(true);
        BtnRujuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRujukActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnRujuk);

        BtnRawatInap.setBackground(new java.awt.Color(195, 205, 185));
        BtnRawatInap.setForeground(new java.awt.Color(153, 0, 51));
        BtnRawatInap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Stethoscope.png"))); // NOI18N
        BtnRawatInap.setMnemonic('O');
        BtnRawatInap.setText("Rw.Inp.Umum");
        BtnRawatInap.setToolTipText("Alt+O");
        BtnRawatInap.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnRawatInap.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnRawatInap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnRawatInap.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnRawatInap.setName("BtnRawatInap"); // NOI18N
        BtnRawatInap.setRoundRect(true);
        BtnRawatInap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRawatInapActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnRawatInap);

        BtnBeriInfus.setBackground(new java.awt.Color(195, 205, 185));
        BtnBeriInfus.setForeground(new java.awt.Color(153, 0, 51));
        BtnBeriInfus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Syringe.png"))); // NOI18N
        BtnBeriInfus.setMnemonic('P');
        BtnBeriInfus.setText("Pb.Infus Umum");
        BtnBeriInfus.setToolTipText("Alt+P");
        BtnBeriInfus.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnBeriInfus.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnBeriInfus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBeriInfus.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnBeriInfus.setName("BtnBeriInfus"); // NOI18N
        BtnBeriInfus.setRoundRect(true);
        BtnBeriInfus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBeriInfusActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnBeriInfus);

        BtnBrObat.setBackground(new java.awt.Color(195, 205, 185));
        BtnBrObat.setForeground(new java.awt.Color(153, 0, 51));
        BtnBrObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Vial-O.png"))); // NOI18N
        BtnBrObat.setMnemonic('Q');
        BtnBrObat.setText("Pb.Obat Umum");
        BtnBrObat.setToolTipText("Alt+Q");
        BtnBrObat.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnBrObat.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnBrObat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBrObat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnBrObat.setName("BtnBrObat"); // NOI18N
        BtnBrObat.setRoundRect(true);
        BtnBrObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBrObatActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnBrObat);

        BtnRwtJlnIbu.setBackground(new java.awt.Color(195, 205, 185));
        BtnRwtJlnIbu.setForeground(new java.awt.Color(153, 0, 51));
        BtnRwtJlnIbu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/addressbook-edit24.png"))); // NOI18N
        BtnRwtJlnIbu.setMnemonic('K');
        BtnRwtJlnIbu.setText("Rw.Jalan Asuransi");
        BtnRwtJlnIbu.setToolTipText("Alt+K");
        BtnRwtJlnIbu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnRwtJlnIbu.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnRwtJlnIbu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnRwtJlnIbu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnRwtJlnIbu.setName("BtnRwtJlnIbu"); // NOI18N
        BtnRwtJlnIbu.setRoundRect(true);
        BtnRwtJlnIbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRwtJlnIbuActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnRwtJlnIbu);

        BtnResepIbu.setBackground(new java.awt.Color(195, 205, 185));
        BtnResepIbu.setForeground(new java.awt.Color(153, 0, 51));
        BtnResepIbu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Drug-basket-32.png"))); // NOI18N
        BtnResepIbu.setMnemonic('L');
        BtnResepIbu.setText("Resep Obat Asuransi");
        BtnResepIbu.setToolTipText("Alt+L");
        BtnResepIbu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnResepIbu.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnResepIbu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnResepIbu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnResepIbu.setName("BtnResepIbu"); // NOI18N
        BtnResepIbu.setRoundRect(true);
        BtnResepIbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResepIbuActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnResepIbu);

        BtnRujukIbu.setBackground(new java.awt.Color(195, 205, 185));
        BtnRujukIbu.setForeground(new java.awt.Color(153, 0, 51));
        BtnRujukIbu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/PSD24.png"))); // NOI18N
        BtnRujukIbu.setMnemonic('M');
        BtnRujukIbu.setText("Rujuk Asuransi");
        BtnRujukIbu.setToolTipText("Alt+M");
        BtnRujukIbu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnRujukIbu.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnRujukIbu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnRujukIbu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnRujukIbu.setName("BtnRujukIbu"); // NOI18N
        BtnRujukIbu.setRoundRect(true);
        BtnRujukIbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRujukIbuActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnRujukIbu);

        BtnRawatInapIbu.setBackground(new java.awt.Color(195, 205, 185));
        BtnRawatInapIbu.setForeground(new java.awt.Color(153, 0, 51));
        BtnRawatInapIbu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Stethoscope.png"))); // NOI18N
        BtnRawatInapIbu.setMnemonic('O');
        BtnRawatInapIbu.setText("Rw.Inap Asuransi");
        BtnRawatInapIbu.setToolTipText("Alt+O");
        BtnRawatInapIbu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnRawatInapIbu.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnRawatInapIbu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnRawatInapIbu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnRawatInapIbu.setName("BtnRawatInapIbu"); // NOI18N
        BtnRawatInapIbu.setRoundRect(true);
        BtnRawatInapIbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRawatInapIbuActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnRawatInapIbu);

        BtnBeriInfusIbu.setBackground(new java.awt.Color(195, 205, 185));
        BtnBeriInfusIbu.setForeground(new java.awt.Color(153, 0, 51));
        BtnBeriInfusIbu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Syringe.png"))); // NOI18N
        BtnBeriInfusIbu.setMnemonic('P');
        BtnBeriInfusIbu.setText("Pb.Infus Asuransi");
        BtnBeriInfusIbu.setToolTipText("Alt+P");
        BtnBeriInfusIbu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnBeriInfusIbu.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnBeriInfusIbu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBeriInfusIbu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnBeriInfusIbu.setName("BtnBeriInfusIbu"); // NOI18N
        BtnBeriInfusIbu.setRoundRect(true);
        BtnBeriInfusIbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBeriInfusIbuActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnBeriInfusIbu);

        BtnBrObatIbu.setBackground(new java.awt.Color(195, 205, 185));
        BtnBrObatIbu.setForeground(new java.awt.Color(153, 0, 51));
        BtnBrObatIbu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Vial-O.png"))); // NOI18N
        BtnBrObatIbu.setMnemonic('Q');
        BtnBrObatIbu.setText("Pb.Obat Asuransi");
        BtnBrObatIbu.setToolTipText("Alt+Q");
        BtnBrObatIbu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnBrObatIbu.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnBrObatIbu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBrObatIbu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnBrObatIbu.setName("BtnBrObatIbu"); // NOI18N
        BtnBrObatIbu.setRoundRect(true);
        BtnBrObatIbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBrObatIbuActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnBrObatIbu);

        BtnRwtJlnBayi.setBackground(new java.awt.Color(195, 205, 185));
        BtnRwtJlnBayi.setForeground(new java.awt.Color(153, 0, 51));
        BtnRwtJlnBayi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/addressbook-edit24.png"))); // NOI18N
        BtnRwtJlnBayi.setMnemonic('K');
        BtnRwtJlnBayi.setText("Rw.Jalan Askes");
        BtnRwtJlnBayi.setToolTipText("Alt+K");
        BtnRwtJlnBayi.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnRwtJlnBayi.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnRwtJlnBayi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnRwtJlnBayi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnRwtJlnBayi.setName("BtnRwtJlnBayi"); // NOI18N
        BtnRwtJlnBayi.setRoundRect(true);
        BtnRwtJlnBayi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRwtJlnBayiActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnRwtJlnBayi);

        BtnResepBayi.setBackground(new java.awt.Color(195, 205, 185));
        BtnResepBayi.setForeground(new java.awt.Color(153, 0, 51));
        BtnResepBayi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Drug-basket-32.png"))); // NOI18N
        BtnResepBayi.setMnemonic('L');
        BtnResepBayi.setText("Resep Obat Askes");
        BtnResepBayi.setToolTipText("Alt+L");
        BtnResepBayi.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnResepBayi.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnResepBayi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnResepBayi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnResepBayi.setName("BtnResepBayi"); // NOI18N
        BtnResepBayi.setRoundRect(true);
        BtnResepBayi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResepBayiActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnResepBayi);

        BtnRujukBayi.setBackground(new java.awt.Color(195, 205, 185));
        BtnRujukBayi.setForeground(new java.awt.Color(153, 0, 51));
        BtnRujukBayi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/PSD24.png"))); // NOI18N
        BtnRujukBayi.setMnemonic('M');
        BtnRujukBayi.setText("Rujuk Askes");
        BtnRujukBayi.setToolTipText("Alt+M");
        BtnRujukBayi.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnRujukBayi.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnRujukBayi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnRujukBayi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnRujukBayi.setName("BtnRujukBayi"); // NOI18N
        BtnRujukBayi.setRoundRect(true);
        BtnRujukBayi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRujukBayiActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnRujukBayi);

        BtnRawatInapBayi.setBackground(new java.awt.Color(195, 205, 185));
        BtnRawatInapBayi.setForeground(new java.awt.Color(153, 0, 51));
        BtnRawatInapBayi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Stethoscope.png"))); // NOI18N
        BtnRawatInapBayi.setMnemonic('O');
        BtnRawatInapBayi.setText("Rwt.Inap Askes");
        BtnRawatInapBayi.setToolTipText("Alt+O");
        BtnRawatInapBayi.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnRawatInapBayi.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnRawatInapBayi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnRawatInapBayi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnRawatInapBayi.setName("BtnRawatInapBayi"); // NOI18N
        BtnRawatInapBayi.setRoundRect(true);
        BtnRawatInapBayi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRawatInapBayiActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnRawatInapBayi);

        BtnBeriInfusBayi.setBackground(new java.awt.Color(195, 205, 185));
        BtnBeriInfusBayi.setForeground(new java.awt.Color(153, 0, 51));
        BtnBeriInfusBayi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Syringe.png"))); // NOI18N
        BtnBeriInfusBayi.setMnemonic('P');
        BtnBeriInfusBayi.setText("Pb.Infus Askes");
        BtnBeriInfusBayi.setToolTipText("Alt+P");
        BtnBeriInfusBayi.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnBeriInfusBayi.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnBeriInfusBayi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBeriInfusBayi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnBeriInfusBayi.setName("BtnBeriInfusBayi"); // NOI18N
        BtnBeriInfusBayi.setRoundRect(true);
        BtnBeriInfusBayi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBeriInfusBayiActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnBeriInfusBayi);

        BtnBrObatBayi.setBackground(new java.awt.Color(195, 205, 185));
        BtnBrObatBayi.setForeground(new java.awt.Color(153, 0, 51));
        BtnBrObatBayi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Vial-O.png"))); // NOI18N
        BtnBrObatBayi.setMnemonic('Q');
        BtnBrObatBayi.setText("Pb.Obat Askes");
        BtnBrObatBayi.setToolTipText("Alt+Q");
        BtnBrObatBayi.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnBrObatBayi.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnBrObatBayi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBrObatBayi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnBrObatBayi.setName("BtnBrObatBayi"); // NOI18N
        BtnBrObatBayi.setRoundRect(true);
        BtnBrObatBayi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBrObatBayiActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnBrObatBayi);

        BtnPasienMati.setBackground(new java.awt.Color(195, 205, 185));
        BtnPasienMati.setForeground(new java.awt.Color(153, 0, 51));
        BtnPasienMati.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/family24.png"))); // NOI18N
        BtnPasienMati.setMnemonic('H');
        BtnPasienMati.setText("Pas.Um.Meninggal");
        BtnPasienMati.setToolTipText("Alt+H");
        BtnPasienMati.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnPasienMati.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnPasienMati.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnPasienMati.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnPasienMati.setName("BtnPasienMati"); // NOI18N
        BtnPasienMati.setRoundRect(true);
        BtnPasienMati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPasienMatiActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnPasienMati);

        BtnIbuMati.setBackground(new java.awt.Color(195, 205, 185));
        BtnIbuMati.setForeground(new java.awt.Color(153, 0, 51));
        BtnIbuMati.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/family24.png"))); // NOI18N
        BtnIbuMati.setMnemonic('H');
        BtnIbuMati.setText("Pas.Asur Meninggal");
        BtnIbuMati.setToolTipText("Alt+H");
        BtnIbuMati.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnIbuMati.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnIbuMati.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnIbuMati.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnIbuMati.setName("BtnIbuMati"); // NOI18N
        BtnIbuMati.setRoundRect(true);
        BtnIbuMati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIbuMatiActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnIbuMati);

        BtnBayiMati.setBackground(new java.awt.Color(195, 205, 185));
        BtnBayiMati.setForeground(new java.awt.Color(153, 0, 51));
        BtnBayiMati.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/family24.png"))); // NOI18N
        BtnBayiMati.setMnemonic('H');
        BtnBayiMati.setText("Pas.Askes.Meninggal");
        BtnBayiMati.setToolTipText("Alt+H");
        BtnBayiMati.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnBayiMati.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnBayiMati.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBayiMati.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnBayiMati.setName("BtnBayiMati"); // NOI18N
        BtnBayiMati.setRoundRect(true);
        BtnBayiMati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBayiMatiActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnBayiMati);

        BtnPesan.setBackground(new java.awt.Color(195, 205, 185));
        BtnPesan.setForeground(new java.awt.Color(153, 0, 51));
        BtnPesan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/mail_search.png"))); // NOI18N
        BtnPesan.setMnemonic('T');
        BtnPesan.setText("Sms Masuk");
        BtnPesan.setToolTipText("Alt+T");
        BtnPesan.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        BtnPesan.setGlassColor(new java.awt.Color(205, 215, 195));
        BtnPesan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnPesan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnPesan.setName("BtnPesan"); // NOI18N
        BtnPesan.setRoundRect(true);
        BtnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesanActionPerformed(evt);
            }
        });
        panelBiasa1.add(BtnPesan);

        internalFrame1.add(panelBiasa1, java.awt.BorderLayout.CENTER);

        panelGlass1.setName("panelGlass1"); // NOI18N
        panelGlass1.setPreferredSize(new java.awt.Dimension(790, 57));
        panelGlass1.setLayout(null);

        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smsimage/control_power.png"))); // NOI18N
        button1.setMnemonic('C');
        button1.setText("Close");
        button1.setToolTipText("Alt+C");
        button1.setName("button1"); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelGlass1.add(button1);
        button1.setBounds(710, 10, 100, 30);

        jLabel12.setForeground(new java.awt.Color(153, 0, 51));
        jLabel12.setText("berelasi juga ikut terhapus. Lakukan backup data terlebih dulu sebelum menghapus isi table");
        jLabel12.setName("jLabel12"); // NOI18N
        panelGlass1.add(jLabel12);
        jLabel12.setBounds(10, 25, 660, 14);

        jLabel11.setForeground(new java.awt.Color(153, 0, 51));
        jLabel11.setText("Berhati-hatilah dalam menghapus isi table. Terdapat relasi antar table, ketika Anda menghapus suatu table maka di table yang");
        jLabel11.setName("jLabel11"); // NOI18N
        panelGlass1.add(jLabel11);
        jLabel11.setBounds(10, 10, 690, 14);

        internalFrame1.add(panelGlass1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        dispose();
}//GEN-LAST:event_button1ActionPerformed

    private void BtnJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJabatanActionPerformed
        hapus("Jabatan","jabatan");
}//GEN-LAST:event_BtnJabatanActionPerformed

    private void BtnSpesialisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSpesialisActionPerformed
        hapus("Spesialis","spesialis");
}//GEN-LAST:event_BtnSpesialisActionPerformed

    private void BtnJIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJIActionPerformed
        hapus("Jenis Infus","jenis_infus");
}//GEN-LAST:event_BtnJIActionPerformed

    private void BtnKPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKPActionPerformed
        hapus("Kategori Perawatan","kategori_perawatan");
}//GEN-LAST:event_BtnKPActionPerformed

    private void BtnJPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJPActionPerformed
        hapus("Jenis Perawatan","jns_perawatan");
}//GEN-LAST:event_BtnJPActionPerformed

    private void BtnKlinikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKlinikActionPerformed
        hapus("Poliklinik","poliklinik");
}//GEN-LAST:event_BtnKlinikActionPerformed

    private void BtnBangsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBangsalActionPerformed
        hapus("Kamar","bangsal");
}//GEN-LAST:event_BtnBangsalActionPerformed

    private void BtnKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKamarActionPerformed
        hapus("Nomor Kamar","kamar");
}//GEN-LAST:event_BtnKamarActionPerformed

    private void BtnKPnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKPnyActionPerformed
        hapus("Kategori Penyakit","kategori_penyakit");
}//GEN-LAST:event_BtnKPnyActionPerformed

    private void BtnPnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPnyActionPerformed
        hapus("Penyakit","penyakit");
}//GEN-LAST:event_BtnPnyActionPerformed

    private void BtnObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnObatActionPerformed
        hapus("Obat","obat");
}//GEN-LAST:event_BtnObatActionPerformed

    private void BtnObatPnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnObatPnyActionPerformed
        hapus("Obat Penyakit","obat_penyakit");
}//GEN-LAST:event_BtnObatPnyActionPerformed

    private void BtnPtgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPtgActionPerformed
        hapus("Petugas","petugas");
}//GEN-LAST:event_BtnPtgActionPerformed

    private void BtnDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDokterActionPerformed
        hapus("Dokter","dokter");
}//GEN-LAST:event_BtnDokterActionPerformed

    private void BtnJadPrakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJadPrakActionPerformed
        hapus("Jadwal Praktek Dokter","jadwal");
}//GEN-LAST:event_BtnJadPrakActionPerformed

    private void BtnPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPasienActionPerformed
        hapus("Pasien Umum","pasien");
}//GEN-LAST:event_BtnPasienActionPerformed

    private void BtnIbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIbuActionPerformed
        hapus("Pasien Ibu","pasien_ibu");
}//GEN-LAST:event_BtnIbuActionPerformed

    private void BtnBayiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBayiActionPerformed
        hapus("Pasien Bayi","pasien_bayi");
}//GEN-LAST:event_BtnBayiActionPerformed

    private void BtnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegActionPerformed
        hapus("Regristrasi Periksa Pasien Umum","reg_periksa");
}//GEN-LAST:event_BtnRegActionPerformed

    private void BtnRegIbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegIbuActionPerformed
        hapus("Regristrasi Periksa Ibu","reg_periksa_ibu");
}//GEN-LAST:event_BtnRegIbuActionPerformed

    private void BtnRegBayiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegBayiActionPerformed
        hapus("Regristrasi Periksa Bayi","reg_periksa_bayi");
}//GEN-LAST:event_BtnRegBayiActionPerformed

    private void BtnKmrInapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKmrInapActionPerformed
        hapus("Kamar Inap Pasien Umum","kamar_inap");
}//GEN-LAST:event_BtnKmrInapActionPerformed

    private void BtnKmrInapIbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKmrInapIbuActionPerformed
        hapus("Kamar Inap Ibu","kamar_inap_ibu");
}//GEN-LAST:event_BtnKmrInapIbuActionPerformed

    private void BtnKmrInapBayiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKmrInapBayiActionPerformed
        hapus("Kamar Inap Bayi","kamar_inap_bayi");
}//GEN-LAST:event_BtnKmrInapBayiActionPerformed

    private void BtnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBillActionPerformed
        hapus("Biaya Perawatan Pasien Umum","billing");
}//GEN-LAST:event_BtnBillActionPerformed

    private void BtnBillIbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBillIbuActionPerformed
        hapus("Biaya Perawatan Ibu","billing_ibu");
}//GEN-LAST:event_BtnBillIbuActionPerformed

    private void BtnBillBayiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBillBayiActionPerformed
        hapus("Biaya Perawatan Bayi","billing_bayi");
}//GEN-LAST:event_BtnBillBayiActionPerformed

    private void BtnRwtJlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRwtJlnActionPerformed
        hapus("Rawat Jalan Umum (Ditangani Dokter)","rawat_jl_dr");
        hapus("Rawat Jalan Umum (Ditangani Perawat)","rawat_jl_pr");
}//GEN-LAST:event_BtnRwtJlnActionPerformed

    private void BtnResepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResepActionPerformed
        hapus("Resep Obat","resep_obat");
}//GEN-LAST:event_BtnResepActionPerformed

    private void BtnRujukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRujukActionPerformed
        hapus("Rujuk Umum","rujuk");
}//GEN-LAST:event_BtnRujukActionPerformed

    private void BtnRawatInapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRawatInapActionPerformed
        hapus("Rawat Inap Ibu (Ditangani Dokter)","rawat_inap_dr");
        hapus("Rawat Inap Ibu (Ditangani Perawat)","rawat_inap_pr");
}//GEN-LAST:event_BtnRawatInapActionPerformed

    private void BtnBeriInfusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBeriInfusActionPerformed
        hapus("Pemberian Infus (Umum)","detail_pemberian_infus");
}//GEN-LAST:event_BtnBeriInfusActionPerformed

    private void BtnBrObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBrObatActionPerformed
        hapus("Pemberian Obat (Umum)","detail_pemberian_obat");
}//GEN-LAST:event_BtnBrObatActionPerformed

    private void BtnRwtJlnIbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRwtJlnIbuActionPerformed
        hapus("Rawat Jalan Ibu (Ditangani Dokter)","rawat_jl_dr_ibu");
        hapus("Rawat Jalan Ibu (Ditangani Perawat)","rawat_jl_pr_ibu");
}//GEN-LAST:event_BtnRwtJlnIbuActionPerformed

    private void BtnResepIbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResepIbuActionPerformed
        hapus("Resep Obat Ibu","resep_obat_ibu");
}//GEN-LAST:event_BtnResepIbuActionPerformed

    private void BtnRujukIbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRujukIbuActionPerformed
        hapus("Rujuk Ibu","rujuk_ibu");
}//GEN-LAST:event_BtnRujukIbuActionPerformed

    private void BtnRawatInapIbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRawatInapIbuActionPerformed
        hapus("Rawat Inap Ibu (Ditangani Dokter)","rawat_inap_dr_ibu");
        hapus("Rawat Inap Ibu (Ditangani Perawat)","rawat_inap_pr_ibu");
}//GEN-LAST:event_BtnRawatInapIbuActionPerformed

    private void BtnBeriInfusIbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBeriInfusIbuActionPerformed
        hapus("Pemberian Infus Ibu","detail_pemberian_infus_ibu");
}//GEN-LAST:event_BtnBeriInfusIbuActionPerformed

    private void BtnBrObatIbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBrObatIbuActionPerformed
        hapus("Pemberian Obat Ibu","detail_pemberian_obat_ibu");
}//GEN-LAST:event_BtnBrObatIbuActionPerformed

    private void BtnRwtJlnBayiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRwtJlnBayiActionPerformed
        hapus("Rawat Jalan Bayi (Ditangani Dokter)","rawat_jl_dr_bayi");
        hapus("Rawat Jalan Bayi (Ditangani Perawat)","rawat_jl_pr_bayi");
}//GEN-LAST:event_BtnRwtJlnBayiActionPerformed

    private void BtnResepBayiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResepBayiActionPerformed
        hapus("Resep Obat Bayi","resep_obat_bayi");
}//GEN-LAST:event_BtnResepBayiActionPerformed

    private void BtnRujukBayiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRujukBayiActionPerformed
        hapus("Rujuk Bayi","rujuk_bayi");
}//GEN-LAST:event_BtnRujukBayiActionPerformed

    private void BtnRawatInapBayiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRawatInapBayiActionPerformed
        hapus("Rawat Inap Bayi (Ditangani Dokter)","rawat_inap_dr_bayi");
        hapus("Rawat Inap Bayi (Ditangani Perawat)","rawat_inap_pr_bayi");
}//GEN-LAST:event_BtnRawatInapBayiActionPerformed

    private void BtnBeriInfusBayiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBeriInfusBayiActionPerformed
        hapus("Pemberian Infus Bayi","detail_pemberian_infus_bayi");
}//GEN-LAST:event_BtnBeriInfusBayiActionPerformed

    private void BtnBrObatBayiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBrObatBayiActionPerformed
        hapus("Pemberian Obat Bayi","detail_pemberian_obat_bayi");
}//GEN-LAST:event_BtnBrObatBayiActionPerformed

    private void BtnPasienMatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPasienMatiActionPerformed
        hapus("Pasien Umum Meninggal","pasien_mati");
}//GEN-LAST:event_BtnPasienMatiActionPerformed

    private void BtnIbuMatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIbuMatiActionPerformed
        hapus("Pasien Ibu Meninggal","pasien_mati_ibu");
}//GEN-LAST:event_BtnIbuMatiActionPerformed

    private void BtnBayiMatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBayiMatiActionPerformed
        hapus("Pasien Bayi Meninggal","pasien_mati_bayi");
}//GEN-LAST:event_BtnBayiMatiActionPerformed

    private void BtnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesanActionPerformed
        hapus("Sms Masuk","sms");
}//GEN-LAST:event_BtnPesanActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgVakum dialog = new DlgVakum(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.ButtonGlass BtnBangsal;
    private usu.widget.ButtonGlass BtnBayi;
    private usu.widget.ButtonGlass BtnBayiMati;
    private usu.widget.ButtonGlass BtnBeriInfus;
    private usu.widget.ButtonGlass BtnBeriInfusBayi;
    private usu.widget.ButtonGlass BtnBeriInfusIbu;
    private usu.widget.ButtonGlass BtnBill;
    private usu.widget.ButtonGlass BtnBillBayi;
    private usu.widget.ButtonGlass BtnBillIbu;
    private usu.widget.ButtonGlass BtnBrObat;
    private usu.widget.ButtonGlass BtnBrObatBayi;
    private usu.widget.ButtonGlass BtnBrObatIbu;
    private usu.widget.ButtonGlass BtnDokter;
    private usu.widget.ButtonGlass BtnIbu;
    private usu.widget.ButtonGlass BtnIbuMati;
    private usu.widget.ButtonGlass BtnJI;
    private usu.widget.ButtonGlass BtnJP;
    private usu.widget.ButtonGlass BtnJabatan;
    private usu.widget.ButtonGlass BtnJadPrak;
    private usu.widget.ButtonGlass BtnKP;
    private usu.widget.ButtonGlass BtnKPny;
    private usu.widget.ButtonGlass BtnKamar;
    private usu.widget.ButtonGlass BtnKlinik;
    private usu.widget.ButtonGlass BtnKmrInap;
    private usu.widget.ButtonGlass BtnKmrInapBayi;
    private usu.widget.ButtonGlass BtnKmrInapIbu;
    private usu.widget.ButtonGlass BtnObat;
    private usu.widget.ButtonGlass BtnObatPny;
    private usu.widget.ButtonGlass BtnPasien;
    private usu.widget.ButtonGlass BtnPasienMati;
    private usu.widget.ButtonGlass BtnPesan;
    private usu.widget.ButtonGlass BtnPny;
    private usu.widget.ButtonGlass BtnPtg;
    private usu.widget.ButtonGlass BtnRawatInap;
    private usu.widget.ButtonGlass BtnRawatInapBayi;
    private usu.widget.ButtonGlass BtnRawatInapIbu;
    private usu.widget.ButtonGlass BtnReg;
    private usu.widget.ButtonGlass BtnRegBayi;
    private usu.widget.ButtonGlass BtnRegIbu;
    private usu.widget.ButtonGlass BtnResep;
    private usu.widget.ButtonGlass BtnResepBayi;
    private usu.widget.ButtonGlass BtnResepIbu;
    private usu.widget.ButtonGlass BtnRujuk;
    private usu.widget.ButtonGlass BtnRujukBayi;
    private usu.widget.ButtonGlass BtnRujukIbu;
    private usu.widget.ButtonGlass BtnRwtJln;
    private usu.widget.ButtonGlass BtnRwtJlnBayi;
    private usu.widget.ButtonGlass BtnRwtJlnIbu;
    private usu.widget.ButtonGlass BtnSpesialis;
    private widget.Button button1;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel11;
    private widget.Label jLabel12;
    private widget.PanelBiasa panelBiasa1;
    private widget.panelisi panelGlass1;
    // End of variables declaration//GEN-END:variables

    public void hapus(String pesan,String nm_table){
        int jawab=JOptionPane.showConfirmDialog(null, "Yakin anda mau menghapuas data "+pesan+" ????","Konfirmasi",JOptionPane.YES_NO_OPTION);
            if(jawab==JOptionPane.YES_OPTION){
                try{
                    java.sql.Statement statement=koneksi.createStatement();
                    statement.executeUpdate("delete from "+nm_table);
                }catch(SQLException e){
                    System.out.println("Pesan Error : "+e);
                    JOptionPane.showMessageDialog(null,"Maaf, Gagal dihapus. Ada sebagian data "+pesan+" yang masih dipakai di table lain...!!!!");
                }
            }
    }
}
