/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgBiling.java
 *
 * Created on 07 Jun 10, 19:07:06
 */

package keuangan;

import fungsi.WarnaTable;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author perpustakaan
 */
public class DlgBilingPiutang extends javax.swing.JDialog {
    private final DefaultTableModel tabModeRwJlDr;
    private String biaya,tambahan,totalx;
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private Jurnal jur=new Jurnal();
    private double total=0;
    private PreparedStatement ps;
    private ResultSet rs;

    /** Creates new form DlgBiling
     * @param parent
     * @param modal */
    public DlgBilingPiutang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(8,1);
        setSize(891,640);

        Object[] rowRwJlDr={"Pilih",
                            "Keterangan",
                            "Tagihan/Tindakan/Terapi",
                            "",
                            "Biaya",
                            "Jumlah",
                            "Tambahan",
                            "Total Biaya",""};
        tabModeRwJlDr=new DefaultTableModel(null,rowRwJlDr){
              @Override public boolean isCellEditable(int rowIndex, int colIndex){
                    return true;
              }
              
              Class[] types = new Class[] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, 
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, 
                java.lang.Object.class
             };
             @Override
             public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
             }
        };
        tbAdmin.setModel(tabModeRwJlDr);

        //tbPetugas.setDefaultRenderer(Object.class, new WarnaTable(panelJudul.getBackground(),tbPetugas.getBackground()));
        tbAdmin.setPreferredScrollableViewportSize(new Dimension(800,800));
        tbAdmin.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        for (int i = 0; i < 9; i++) {
            TableColumn column = tbAdmin.getColumnModel().getColumn(i);
            if(i==0){
                column.setPreferredWidth(40);
            }else if(i==1){
                column.setPreferredWidth(130);
            }else if(i==2){
                column.setPreferredWidth(450);
            }else if(i==3){
                column.setPreferredWidth(15);
            }else if(i==4){
                column.setPreferredWidth(140);
            }else if(i==5){
                column.setPreferredWidth(60);
            }else if(i==6){
                column.setPreferredWidth(140);
            }else if(i==7){
                column.setPreferredWidth(200);
            }else if(i==8){
                column.setPreferredWidth(10);
            }
        }

        tbAdmin.setDefaultRenderer(Object.class, new WarnaTable());

        try {
            ps=koneksi.prepareStatement("select no,nm_perawatan, if(biaya<>0,biaya,'') as satu, if(jumlah<>0,jumlah,'') as dua,"+
                        "if(tambahan<>0,tambahan,'') as tiga, if(totalbiaya<>0,totalbiaya,'') as empat,pemisah,status "+
                        "from billing where no_rawat=?  order by noindex");
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbAdmin = new widget.Table();
        panelisi1 = new widget.panelisi();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Rincian Piutang Pasien ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 70, 40))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbAdmin.setAutoCreateRowSorter(true);
        tbAdmin.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbAdmin.setName("tbAdmin"); // NOI18N
        Scroll.setViewportView(tbAdmin);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        panelisi1.add(BtnPrint);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if(tabModeRwJlDr.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, data sudah habis. Tidak ada data yang bisa anda print...!!!!");
            BtnKeluar.requestFocus();
        }else if(tabModeRwJlDr.getRowCount()!=0){            
            Sequel.queryu("delete from temporary_bayar_ralan");
                int row=tabModeRwJlDr.getRowCount();
                for(int r=0;r<row;r++){  
                    if(tabModeRwJlDr.getValueAt(r,0).toString().equals("true")){
                        biaya="";
                        if(!tabModeRwJlDr.getValueAt(r,4).toString().isEmpty()){
                            biaya=Valid.SetAngka(Double.parseDouble(tabModeRwJlDr.getValueAt(r,4).toString()));
                        }
                        tambahan="";
                        if(!tabModeRwJlDr.getValueAt(r,6).toString().isEmpty()){
                            tambahan=Valid.SetAngka(Double.parseDouble(tabModeRwJlDr.getValueAt(r,6).toString()));
                        }
                        totalx="";
                        if(!tabModeRwJlDr.getValueAt(r,7).toString().isEmpty()){
                            totalx=Valid.SetAngka(Double.parseDouble(tabModeRwJlDr.getValueAt(r,7).toString()));
                        }
                        Sequel.menyimpan("temporary_bayar_ralan","'0','"+
                                        tabModeRwJlDr.getValueAt(r,1).toString().replaceAll("'","`") +"','"+
                                        tabModeRwJlDr.getValueAt(r,2).toString().replaceAll("'","`")+"','"+
                                        tabModeRwJlDr.getValueAt(r,3).toString().replaceAll("'","`")+"','"+
                                        biaya+"','"+
                                        tabModeRwJlDr.getValueAt(r,5).toString().replaceAll("'","`")+"','"+
                                        tambahan+"','"+
                                        totalx+"','','','','','','','','','',''","Rekap Nota Pembayaran"); 
                    }              
                }
                    Valid.panggilUrl("billing/LaporanBilling.php");  
        }
        this.setCursor(Cursor.getDefaultCursor());
}//GEN-LAST:event_BtnPrintActionPerformed

private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPrintKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnPrintActionPerformed(null);
        }else{
            Valid.pindah(evt, BtnPrint, BtnKeluar);
        }
}//GEN-LAST:event_BtnPrintKeyPressed

private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            dispose();
        }else{Valid.pindah(evt,BtnKeluar,BtnPrint);}
}//GEN-LAST:event_BtnKeluarKeyPressed



    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgBilingPiutang dialog = new DlgBilingPiutang(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.ScrollPane Scroll;
    private widget.InternalFrame internalFrame1;
    private widget.panelisi panelisi1;
    private widget.Table tbAdmin;
    // End of variables declaration//GEN-END:variables

    public void isRawat(String norawat) {
             try{
                ps.setString(1, norawat);
                rs=ps.executeQuery();
                total=0;
                while(rs.next()){
                        tabModeRwJlDr.addRow(new Object[]{true,rs.getString("no"),
                                    rs.getString("nm_perawatan"),
                                    rs.getString("pemisah"),
                                    rs.getString("satu"),
                                    rs.getString("dua"),
                                    rs.getString("tiga"),
                                    rs.getString("empat"),
                                    rs.getString("status")});  
                        if(rs.getDouble("empat")>0){
                            total=total+rs.getDouble("empat");
                        }
                }
                tabModeRwJlDr.addRow(new Object[]{true,"","Total :","","","","",total,""});  
            }catch(SQLException e){
                System.out.println("Error : "+e);
            }
    }

    
}
